// NOTICE:
// This file is generated by corresponding ".tt" file template, do NOT modify this file.

using Althea.NativeTypes;
using Althea.Storage;
using Althea.SourceGenerator;


namespace Althea.Random
{
	#region distributions
	/// <summary>
	/// The abstract class for a one-dimensional distribution.
	/// </summary>
	/// <typeparam name="T">Any unmanaged number as the data type</typeparam>
	public abstract class Rank1RandomDistribution<T> : IRandomDistribution where T : unmanaged, INumber<T>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank) => rank == 0 ? Unmanaged<T>.DataType : throw new ArgumentOutOfRangeException(nameof(rank));

		/// <inheritdoc/>
		public static int Rank => 1;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}

	/// <summary>
	/// The abstract class for a two-dimensional distribution.
	/// </summary>
	/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
	/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
	public abstract class Rank2RandomDistribution<T1, T2> : IRandomDistribution where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank)
		{
			return rank switch
			{
				0 => Unmanaged<T1>.DataType,
				1 => Unmanaged<T2>.DataType,
				_ => throw new ArgumentOutOfRangeException(nameof(rank)),
			};
		}

		/// <inheritdoc/>
		public static int Rank => 2;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}

	/// <summary>
	/// The abstract class for a three-dimensional distribution.
	/// </summary>
	/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
	/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
	/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
	public abstract class Rank3RandomDistribution<T1, T2, T3> : IRandomDistribution where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank)
		{
			return rank switch
			{
				0 => Unmanaged<T1>.DataType,
				1 => Unmanaged<T2>.DataType,
				2 => Unmanaged<T3>.DataType,
				_ => throw new ArgumentOutOfRangeException(nameof(rank)),
			};
		}

		/// <inheritdoc/>
		public static int Rank => 3;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}

	/// <summary>
	/// The abstract class for a four-dimensional distribution.
	/// </summary>
	/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
	/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
	/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
	/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
	public abstract class Rank4RandomDistribution<T1, T2, T3, T4> : IRandomDistribution where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank)
		{
			return rank switch
			{
				0 => Unmanaged<T1>.DataType,
				1 => Unmanaged<T2>.DataType,
				2 => Unmanaged<T3>.DataType,
				3 => Unmanaged<T4>.DataType,
				_ => throw new ArgumentOutOfRangeException(nameof(rank)),
			};
		}

		/// <inheritdoc/>
		public static int Rank => 4;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}

	/// <summary>
	/// The abstract class for a five-dimensional distribution.
	/// </summary>
	/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
	/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
	/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
	/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
	/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
	public abstract class Rank5RandomDistribution<T1, T2, T3, T4, T5> : IRandomDistribution where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank)
		{
			return rank switch
			{
				0 => Unmanaged<T1>.DataType,
				1 => Unmanaged<T2>.DataType,
				2 => Unmanaged<T3>.DataType,
				3 => Unmanaged<T4>.DataType,
				4 => Unmanaged<T5>.DataType,
				_ => throw new ArgumentOutOfRangeException(nameof(rank)),
			};
		}

		/// <inheritdoc/>
		public static int Rank => 5;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}

	/// <summary>
	/// The abstract class for a six-dimensional distribution.
	/// </summary>
	/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
	/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
	/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
	/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
	/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
	/// <typeparam name="T6">Any unmanaged number as the sixth data type</typeparam>
	public abstract class Rank6RandomDistribution<T1, T2, T3, T4, T5, T6> : IRandomDistribution where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where T6 : unmanaged, INumber<T6>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank)
		{
			return rank switch
			{
				0 => Unmanaged<T1>.DataType,
				1 => Unmanaged<T2>.DataType,
				2 => Unmanaged<T3>.DataType,
				3 => Unmanaged<T4>.DataType,
				4 => Unmanaged<T5>.DataType,
				5 => Unmanaged<T6>.DataType,
				_ => throw new ArgumentOutOfRangeException(nameof(rank)),
			};
		}

		/// <inheritdoc/>
		public static int Rank => 6;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}

	/// <summary>
	/// The abstract class for a seven-dimensional distribution.
	/// </summary>
	/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
	/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
	/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
	/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
	/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
	/// <typeparam name="T6">Any unmanaged number as the sixth data type</typeparam>
	/// <typeparam name="T7">Any unmanaged number as the seventh data type</typeparam>
	public abstract class Rank7RandomDistribution<T1, T2, T3, T4, T5, T6, T7> : IRandomDistribution where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where T6 : unmanaged, INumber<T6> where T7 : unmanaged, INumber<T7>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank)
		{
			return rank switch
			{
				0 => Unmanaged<T1>.DataType,
				1 => Unmanaged<T2>.DataType,
				2 => Unmanaged<T3>.DataType,
				3 => Unmanaged<T4>.DataType,
				4 => Unmanaged<T5>.DataType,
				5 => Unmanaged<T6>.DataType,
				6 => Unmanaged<T7>.DataType,
				_ => throw new ArgumentOutOfRangeException(nameof(rank)),
			};
		}

		/// <inheritdoc/>
		public static int Rank => 7;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}

	/// <summary>
	/// The abstract class for a eight-dimensional distribution.
	/// </summary>
	/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
	/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
	/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
	/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
	/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
	/// <typeparam name="T6">Any unmanaged number as the sixth data type</typeparam>
	/// <typeparam name="T7">Any unmanaged number as the seventh data type</typeparam>
	/// <typeparam name="T8">Any unmanaged number as the eighth data type</typeparam>
	public abstract class Rank8RandomDistribution<T1, T2, T3, T4, T5, T6, T7, T8> : IRandomDistribution where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where T6 : unmanaged, INumber<T6> where T7 : unmanaged, INumber<T7> where T8 : unmanaged, INumber<T8>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank)
		{
			return rank switch
			{
				0 => Unmanaged<T1>.DataType,
				1 => Unmanaged<T2>.DataType,
				2 => Unmanaged<T3>.DataType,
				3 => Unmanaged<T4>.DataType,
				4 => Unmanaged<T5>.DataType,
				5 => Unmanaged<T6>.DataType,
				6 => Unmanaged<T7>.DataType,
				7 => Unmanaged<T8>.DataType,
				_ => throw new ArgumentOutOfRangeException(nameof(rank)),
			};
		}

		/// <inheritdoc/>
		public static int Rank => 8;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}

	/// <summary>
	/// The abstract class for a nine-dimensional distribution.
	/// </summary>
	/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
	/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
	/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
	/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
	/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
	/// <typeparam name="T6">Any unmanaged number as the sixth data type</typeparam>
	/// <typeparam name="T7">Any unmanaged number as the seventh data type</typeparam>
	/// <typeparam name="T8">Any unmanaged number as the eighth data type</typeparam>
	/// <typeparam name="T9">Any unmanaged number as the ninth data type</typeparam>
	public abstract class Rank9RandomDistribution<T1, T2, T3, T4, T5, T6, T7, T8, T9> : IRandomDistribution where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where T6 : unmanaged, INumber<T6> where T7 : unmanaged, INumber<T7> where T8 : unmanaged, INumber<T8> where T9 : unmanaged, INumber<T9>
	{
		/// <inheritdoc/>
		public static DataType DataTypeAt(int rank)
		{
			return rank switch
			{
				0 => Unmanaged<T1>.DataType,
				1 => Unmanaged<T2>.DataType,
				2 => Unmanaged<T3>.DataType,
				3 => Unmanaged<T4>.DataType,
				4 => Unmanaged<T5>.DataType,
				5 => Unmanaged<T6>.DataType,
				6 => Unmanaged<T7>.DataType,
				7 => Unmanaged<T8>.DataType,
				8 => Unmanaged<T9>.DataType,
				_ => throw new ArgumentOutOfRangeException(nameof(rank)),
			};
		}

		/// <inheritdoc/>
		public static int Rank => 9;

		/// <inheritdoc/>
		public abstract long? RandomSeed { get; }
	}
	#endregion

	#region API
	/// <summary>
	/// The abstract interface for runtime random API routines 
	/// </summary>
	[AbstractRuntimeApi]
	public interface IAbstractApi : IAbstractRuntimeApi<IAbstractApi>
	{
		/// <summary>
		/// When implemented by a derived class, fill the given <paramref name="storage"/> with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T">Any unmanaged number as the data type</typeparam>
		/// <typeparam name="TS">The storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage">The storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="IRandomDistribution"/> indicating which distribution to use, must be of rank-1</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If <paramref name="storage"/> is null or invalid</exception>
		/// <exception cref="ArgumentException">If <paramref name="distribution"/> is not of rank-1 or its data type is not <typeparamref name="T"/></exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T, TS>(TS storage, IRandomDistribution distribution) where T : unmanaged, INumber<T> where TS : class, IStorage<T, TS>;

		/// <summary>
		/// When implemented by a derived class, fill the given storages with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
		/// <typeparam name="TS1">The first storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
		/// <typeparam name="TS2">The second storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage1">The first storage to be filled with random numbers</param>
		/// <param name="storage2">The second storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="Rank2RandomDistribution{T1, T2}"/> indicating which distribution to use</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T1, T2, TS1, TS2>(TS1 storage1, TS2 storage2, Rank2RandomDistribution<T1, T2> distribution) where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where TS1 : class, IStorage<T1, TS1> where TS2 : class, IStorage<T2, TS2>;

		/// <summary>
		/// When implemented by a derived class, fill the given storages with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
		/// <typeparam name="TS1">The first storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
		/// <typeparam name="TS2">The second storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
		/// <typeparam name="TS3">The third storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage1">The first storage to be filled with random numbers</param>
		/// <param name="storage2">The second storage to be filled with random numbers</param>
		/// <param name="storage3">The third storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="Rank3RandomDistribution{T1, T2, T3}"/> indicating which distribution to use</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T1, T2, T3, TS1, TS2, TS3>(TS1 storage1, TS2 storage2, TS3 storage3, Rank3RandomDistribution<T1, T2, T3> distribution) where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where TS1 : class, IStorage<T1, TS1> where TS2 : class, IStorage<T2, TS2> where TS3 : class, IStorage<T3, TS3>;

		/// <summary>
		/// When implemented by a derived class, fill the given storages with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
		/// <typeparam name="TS1">The first storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
		/// <typeparam name="TS2">The second storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
		/// <typeparam name="TS3">The third storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
		/// <typeparam name="TS4">The fourth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage1">The first storage to be filled with random numbers</param>
		/// <param name="storage2">The second storage to be filled with random numbers</param>
		/// <param name="storage3">The third storage to be filled with random numbers</param>
		/// <param name="storage4">The fourth storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="Rank4RandomDistribution{T1, T2, T3, T4}"/> indicating which distribution to use</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T1, T2, T3, T4, TS1, TS2, TS3, TS4>(TS1 storage1, TS2 storage2, TS3 storage3, TS4 storage4, Rank4RandomDistribution<T1, T2, T3, T4> distribution) where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where TS1 : class, IStorage<T1, TS1> where TS2 : class, IStorage<T2, TS2> where TS3 : class, IStorage<T3, TS3> where TS4 : class, IStorage<T4, TS4>;

		/// <summary>
		/// When implemented by a derived class, fill the given storages with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
		/// <typeparam name="TS1">The first storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
		/// <typeparam name="TS2">The second storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
		/// <typeparam name="TS3">The third storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
		/// <typeparam name="TS4">The fourth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
		/// <typeparam name="TS5">The fifth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage1">The first storage to be filled with random numbers</param>
		/// <param name="storage2">The second storage to be filled with random numbers</param>
		/// <param name="storage3">The third storage to be filled with random numbers</param>
		/// <param name="storage4">The fourth storage to be filled with random numbers</param>
		/// <param name="storage5">The fifth storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="Rank5RandomDistribution{T1, T2, T3, T4, T5}"/> indicating which distribution to use</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T1, T2, T3, T4, T5, TS1, TS2, TS3, TS4, TS5>(TS1 storage1, TS2 storage2, TS3 storage3, TS4 storage4, TS5 storage5, Rank5RandomDistribution<T1, T2, T3, T4, T5> distribution) where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where TS1 : class, IStorage<T1, TS1> where TS2 : class, IStorage<T2, TS2> where TS3 : class, IStorage<T3, TS3> where TS4 : class, IStorage<T4, TS4> where TS5 : class, IStorage<T5, TS5>;

		/// <summary>
		/// When implemented by a derived class, fill the given storages with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
		/// <typeparam name="TS1">The first storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
		/// <typeparam name="TS2">The second storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
		/// <typeparam name="TS3">The third storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
		/// <typeparam name="TS4">The fourth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
		/// <typeparam name="TS5">The fifth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T6">Any unmanaged number as the sixth data type</typeparam>
		/// <typeparam name="TS6">The sixth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage1">The first storage to be filled with random numbers</param>
		/// <param name="storage2">The second storage to be filled with random numbers</param>
		/// <param name="storage3">The third storage to be filled with random numbers</param>
		/// <param name="storage4">The fourth storage to be filled with random numbers</param>
		/// <param name="storage5">The fifth storage to be filled with random numbers</param>
		/// <param name="storage6">The sixth storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="Rank6RandomDistribution{T1, T2, T3, T4, T5, T6}"/> indicating which distribution to use</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T1, T2, T3, T4, T5, T6, TS1, TS2, TS3, TS4, TS5, TS6>(TS1 storage1, TS2 storage2, TS3 storage3, TS4 storage4, TS5 storage5, TS6 storage6, Rank6RandomDistribution<T1, T2, T3, T4, T5, T6> distribution) where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where T6 : unmanaged, INumber<T6> where TS1 : class, IStorage<T1, TS1> where TS2 : class, IStorage<T2, TS2> where TS3 : class, IStorage<T3, TS3> where TS4 : class, IStorage<T4, TS4> where TS5 : class, IStorage<T5, TS5> where TS6 : class, IStorage<T6, TS6>;

		/// <summary>
		/// When implemented by a derived class, fill the given storages with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
		/// <typeparam name="TS1">The first storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
		/// <typeparam name="TS2">The second storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
		/// <typeparam name="TS3">The third storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
		/// <typeparam name="TS4">The fourth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
		/// <typeparam name="TS5">The fifth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T6">Any unmanaged number as the sixth data type</typeparam>
		/// <typeparam name="TS6">The sixth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T7">Any unmanaged number as the seventh data type</typeparam>
		/// <typeparam name="TS7">The seventh storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage1">The first storage to be filled with random numbers</param>
		/// <param name="storage2">The second storage to be filled with random numbers</param>
		/// <param name="storage3">The third storage to be filled with random numbers</param>
		/// <param name="storage4">The fourth storage to be filled with random numbers</param>
		/// <param name="storage5">The fifth storage to be filled with random numbers</param>
		/// <param name="storage6">The sixth storage to be filled with random numbers</param>
		/// <param name="storage7">The seventh storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="Rank7RandomDistribution{T1, T2, T3, T4, T5, T6, T7}"/> indicating which distribution to use</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T1, T2, T3, T4, T5, T6, T7, TS1, TS2, TS3, TS4, TS5, TS6, TS7>(TS1 storage1, TS2 storage2, TS3 storage3, TS4 storage4, TS5 storage5, TS6 storage6, TS7 storage7, Rank7RandomDistribution<T1, T2, T3, T4, T5, T6, T7> distribution) where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where T6 : unmanaged, INumber<T6> where T7 : unmanaged, INumber<T7> where TS1 : class, IStorage<T1, TS1> where TS2 : class, IStorage<T2, TS2> where TS3 : class, IStorage<T3, TS3> where TS4 : class, IStorage<T4, TS4> where TS5 : class, IStorage<T5, TS5> where TS6 : class, IStorage<T6, TS6> where TS7 : class, IStorage<T7, TS7>;

		/// <summary>
		/// When implemented by a derived class, fill the given storages with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
		/// <typeparam name="TS1">The first storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
		/// <typeparam name="TS2">The second storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
		/// <typeparam name="TS3">The third storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
		/// <typeparam name="TS4">The fourth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
		/// <typeparam name="TS5">The fifth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T6">Any unmanaged number as the sixth data type</typeparam>
		/// <typeparam name="TS6">The sixth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T7">Any unmanaged number as the seventh data type</typeparam>
		/// <typeparam name="TS7">The seventh storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T8">Any unmanaged number as the eighth data type</typeparam>
		/// <typeparam name="TS8">The eighth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage1">The first storage to be filled with random numbers</param>
		/// <param name="storage2">The second storage to be filled with random numbers</param>
		/// <param name="storage3">The third storage to be filled with random numbers</param>
		/// <param name="storage4">The fourth storage to be filled with random numbers</param>
		/// <param name="storage5">The fifth storage to be filled with random numbers</param>
		/// <param name="storage6">The sixth storage to be filled with random numbers</param>
		/// <param name="storage7">The seventh storage to be filled with random numbers</param>
		/// <param name="storage8">The eighth storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="Rank8RandomDistribution{T1, T2, T3, T4, T5, T6, T7, T8}"/> indicating which distribution to use</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T1, T2, T3, T4, T5, T6, T7, T8, TS1, TS2, TS3, TS4, TS5, TS6, TS7, TS8>(TS1 storage1, TS2 storage2, TS3 storage3, TS4 storage4, TS5 storage5, TS6 storage6, TS7 storage7, TS8 storage8, Rank8RandomDistribution<T1, T2, T3, T4, T5, T6, T7, T8> distribution) where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where T6 : unmanaged, INumber<T6> where T7 : unmanaged, INumber<T7> where T8 : unmanaged, INumber<T8> where TS1 : class, IStorage<T1, TS1> where TS2 : class, IStorage<T2, TS2> where TS3 : class, IStorage<T3, TS3> where TS4 : class, IStorage<T4, TS4> where TS5 : class, IStorage<T5, TS5> where TS6 : class, IStorage<T6, TS6> where TS7 : class, IStorage<T7, TS7> where TS8 : class, IStorage<T8, TS8>;

		/// <summary>
		/// When implemented by a derived class, fill the given storages with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <typeparam name="T1">Any unmanaged number as the first data type</typeparam>
		/// <typeparam name="TS1">The first storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second data type</typeparam>
		/// <typeparam name="TS2">The second storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third data type</typeparam>
		/// <typeparam name="TS3">The third storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T4">Any unmanaged number as the fourth data type</typeparam>
		/// <typeparam name="TS4">The fourth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T5">Any unmanaged number as the fifth data type</typeparam>
		/// <typeparam name="TS5">The fifth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T6">Any unmanaged number as the sixth data type</typeparam>
		/// <typeparam name="TS6">The sixth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T7">Any unmanaged number as the seventh data type</typeparam>
		/// <typeparam name="TS7">The seventh storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T8">Any unmanaged number as the eighth data type</typeparam>
		/// <typeparam name="TS8">The eighth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T9">Any unmanaged number as the ninth data type</typeparam>
		/// <typeparam name="TS9">The ninth storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="storage1">The first storage to be filled with random numbers</param>
		/// <param name="storage2">The second storage to be filled with random numbers</param>
		/// <param name="storage3">The third storage to be filled with random numbers</param>
		/// <param name="storage4">The fourth storage to be filled with random numbers</param>
		/// <param name="storage5">The fifth storage to be filled with random numbers</param>
		/// <param name="storage6">The sixth storage to be filled with random numbers</param>
		/// <param name="storage7">The seventh storage to be filled with random numbers</param>
		/// <param name="storage8">The eighth storage to be filled with random numbers</param>
		/// <param name="storage9">The ninth storage to be filled with random numbers</param>
		/// <param name="distribution">The <see cref="Rank9RandomDistribution{T1, T2, T3, T4, T5, T6, T7, T8, T9}"/> indicating which distribution to use</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom<T1, T2, T3, T4, T5, T6, T7, T8, T9, TS1, TS2, TS3, TS4, TS5, TS6, TS7, TS8, TS9>(TS1 storage1, TS2 storage2, TS3 storage3, TS4 storage4, TS5 storage5, TS6 storage6, TS7 storage7, TS8 storage8, TS9 storage9, Rank9RandomDistribution<T1, T2, T3, T4, T5, T6, T7, T8, T9> distribution) where T1 : unmanaged, INumber<T1> where T2 : unmanaged, INumber<T2> where T3 : unmanaged, INumber<T3> where T4 : unmanaged, INumber<T4> where T5 : unmanaged, INumber<T5> where T6 : unmanaged, INumber<T6> where T7 : unmanaged, INumber<T7> where T8 : unmanaged, INumber<T8> where T9 : unmanaged, INumber<T9> where TS1 : class, IStorage<T1, TS1> where TS2 : class, IStorage<T2, TS2> where TS3 : class, IStorage<T3, TS3> where TS4 : class, IStorage<T4, TS4> where TS5 : class, IStorage<T5, TS5> where TS6 : class, IStorage<T6, TS6> where TS7 : class, IStorage<T7, TS7> where TS8 : class, IStorage<T8, TS8> where TS9 : class, IStorage<T9, TS9>;

		/// <summary>
		/// When implemented by a derived class, fill the given <paramref name="storages"/> with random numbers generated from the given <paramref name="distribution"/>
		/// </summary>
		/// <param name="distribution">The <see cref="IRandomDistribution"/> indicating which distribution to use, must be of rank equaling the length of <paramref name="storages"/></param>
		/// <param name="storages">The array of <see cref="IStorage"/>s to be filled with random numbers</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of <paramref name="storages"/> is null or invalid</exception>
		/// <exception cref="ArgumentException">If <paramref name="distribution"/> is of wrong rank or its data types are not the data types of <paramref name="storages"/></exception>
		[AbstractApiMethod]
		public abstract bool FillWithRandom(IRandomDistribution distribution, params IStorage[] storages);
	}
	#endregion
}
