<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<TargetFramework>net7.0</TargetFramework>
	<LangVersion>preview</LangVersion>
	<EnablePreviewFeatures>True</EnablePreviewFeatures>
	<Platforms>x64</Platforms>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<Nullable>enable</Nullable>
  </PropertyGroup>
  
  <PropertyGroup>
	<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
	<RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
	<RootNamespace>Althea.GeneralSolvers</RootNamespace>
	<AssemblyName>Althea.GeneralSolvers</AssemblyName>
	<AnalysisLevel>latest</AnalysisLevel>
	<RepositoryUrl>https://github.com/sses7757/Althea</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.CodeAnalysis.Metrics" Version="3.3.3" />
  </ItemGroup>
  
  <ItemGroup>
	<ProjectReference Include="..\Althea.Backend\Althea.Backend.csproj" />
	<ProjectReference Include="..\Althea\Althea.csproj" />
  </ItemGroup>
  
  <ItemGroup>
	<Compile Update="Krylov\Resource.Designer.cs">
	  <DependentUpon>Resource.resx</DependentUpon>
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	</Compile>
  </ItemGroup>
  
  <ItemGroup>
	<EmbeddedResource Update="Krylov\Resource.resx">
	  <LastGenOutput>Resource.Designer.cs</LastGenOutput>
	  <Generator>ResXFileCodeGenerator</Generator>
	</EmbeddedResource>
  </ItemGroup>

  <PropertyGroup Condition=" '$(Platform)' == 'x64' ">
	<DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug'">
	<DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
	<DocumentationFile>$(MSBuildProjectDirectory)\documents\$(MSBuildProjectName).xml</DocumentationFile>
	<NoWarn>1701;1702</NoWarn>
	<Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
	<DocumentationFile>$(MSBuildProjectDirectory)\documents\$(MSBuildProjectName).xml</DocumentationFile>
	<LangVersion>preview</LangVersion>
  </PropertyGroup>

</Project>
