using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace Althea.Solver.Mkl
{
	/// <summary>
	/// MKL Solver library API
	/// </summary>
	public static class NativeMethods
	{
		/// <summary>
		/// The MKL Solver library name
		/// </summary>
		public const string MKLBLAS_API_DLL_NAME = "mkl_rt";

		/// <summary>
		/// Computes the LU factorization of a general matrix.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix</param>
		/// <param name="m">number of rows of <paramref name="A"/></param>
		/// <param name="n">number of columns of <paramref name="A"/></param>
		/// <param name="A">matrix with size <paramref name="lda"/>×<paramref name="n"/>, will be overwritten by L and U.</param>
		/// <param name="lda">leading dimension of <paramref name="A"/></param>
		/// <param name="ipiv">Array, size at least max(1,min(m, n)). Contains the pivot indices; for <c>1 ≤ i,j ≤ min(<paramref name="m"/>, <paramref name="n"/>)</c>, row <c>i</c> was interchanged with row <c>j</c></param>
		/// <returns>This function returns a value info. If <c>info = 0</c>, the execution is successful. If <c>info = -i</c>, parameter <c>i</c> had an illegal value. If <c>info = i</c>, <c>U<sub>ii</sub></c> is 0. The factorization has been completed, but U is exactly singular. Division by 0 will occur if you use the factor U for solving a system of linear equations.</returns>
		internal delegate int getrfFunc(MklSolverLayout matrix_layout, int m, int n, IntPtr A, int lda, IntPtr ipiv);
		#region LU factorization

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_sgetrf(MklSolverLayout matrix_layout, int m, int n, IntPtr A, int lda, IntPtr ipiv);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_dgetrf(MklSolverLayout matrix_layout, int m, int n, IntPtr A, int lda, IntPtr ipiv);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_cgetrf(MklSolverLayout matrix_layout, int m, int n, IntPtr A, int lda, IntPtr ipiv);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_zgetrf(MklSolverLayout matrix_layout, int m, int n, IntPtr A, int lda, IntPtr ipiv);
		#endregion

		/// <summary>
		/// Solve linear systems where <paramref name="A"/> is generated by <see cref="getrfFunc"/>.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix</param>
		/// <param name="trans">see <see cref="Blas.Mkl.NativeMethods.geamFunc{T}"/></param>
		/// <param name="n">number of rows and columns of <paramref name="A"/></param>
		/// <param name="nrhs">number of columns of <paramref name="B"/></param>
		/// <param name="A">matrix with size <paramref name="lda"/>×<paramref name="n"/>, will be overwritten by L and U.</param>
		/// <param name="lda">leading dimension of <paramref name="A"/></param>
		/// <param name="ipiv">Array, size at least <paramref name="n"/>. Contains the pivot indices; for <c>1 ≤ i,j ≤ min(<paramref name="n"/>, <paramref name="n"/>)</c>, row <c>i</c> was interchanged with row <c>j</c></param>
		/// <param name="B">matrix at right side with size <paramref name="ldb"/>×<paramref name="nrhs"/></param>
		/// <param name="ldb">leading dimension of <paramref name="B"/></param>
		/// <returns>This function returns a value info. If <c>info = 0</c>, the execution is successful. If <c>info = -i</c>, parameter <c>i</c> had an illegal value. If <c>info = i</c>, <c>U</c> is singular since <c>U<sub>ii</sub></c> is 0.</returns>
		internal delegate int getrsFunc(MklSolverLayout matrix_layout, byte trans, int n, int nrhs, [In] IntPtr A, int lda, [In] IntPtr ipiv, IntPtr B, int ldb);
		#region LU solve
		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_sgetrs(MklSolverLayout matrix_layout, byte trans, int n, int nrhs, [In] IntPtr A, int lda, [In] IntPtr ipiv, IntPtr B, int ldb);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_dgetrs(MklSolverLayout matrix_layout, byte trans, int n, int nrhs, [In] IntPtr A, int lda, [In] IntPtr ipiv, IntPtr b, int ldb);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_cgetrs(MklSolverLayout matrix_layout, byte trans, int n, int nrhs, [In] IntPtr A, int lda, [In] IntPtr ipiv, IntPtr b, int ldb);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_zgetrs(MklSolverLayout matrix_layout, byte trans, int n, int nrhs, [In] IntPtr A, int lda, [In] IntPtr ipiv, IntPtr b, int ldb);
		#endregion

		/// <summary>
		/// This function computes the QR factorization of matrix.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix <paramref name="A"/>.</param>
		/// <param name="m">number of rows of matrix <paramref name="A"/>.</param>
		/// <param name="n">number of columns of matrix <paramref name="A"/>.</param>
		/// <param name="A">matrix of dimension <paramref name="lda"/>×<paramref name="n"/> with <paramref name="lda"/> is not less than <c>max(1, <paramref name="m"/>)</c>. The matrix R is overwritten in upper triangular part of A, including diagonal elements.</param>
		/// <param name="lda">leading dimension of two-dimensional array used to store matrix <paramref name="A"/>.</param>
		/// <param name="tau">pre-allocated array of dimension at least<c> min(m,n)</c>, contains the scalars of elementary reflection vectors.</param>
		/// <returns>The info. If <c>info = 0</c>, the LU factorization is successful. if <c>info = -i</c>, the i-th parameter is wrong.</returns>
		internal delegate int geqrfFunc(MklSolverLayout matrix_layout, int m, int n, IntPtr A, int lda, IntPtr tau);

		/// <summary>
		/// This function overwrites m×n matrix <paramref name="A"/> by <c>Q = H(1) * H(2) * ... * H(k)</c> where Q is a unitary matrix formed by a sequence of elementary reflection vectors stored in <paramref name="A"/>.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix <paramref name="A"/>.</param>
		/// <param name="m">number of rows of matrix <paramref name="A"/>.</param>
		/// <param name="n">number of columns of matrix <paramref name="A"/>.</param>
		/// <param name="k">number of elementary reflections whose product defines the matrix Q, <paramref name="k"/>≤<paramref name="n"/></param>
		/// <param name="A">array of dimension <paramref name="lda"/>×<paramref name="n"/> with <paramref name="lda"/> is not less than <c>max(1, <paramref name="m"/>)</c>.</param>
		/// <param name="lda">leading dimension of two-dimensional array used to store matrix <paramref name="A"/>.</param>
		/// <param name="tau">the scalars of elementary reflection vectors</param>
		/// <returns>The info. If <c>info = 0</c>, the LU factorization is successful. if <c>info = -i</c>, the i-th parameter is wrong.</returns>
		internal delegate int orgqrFunc(MklSolverLayout matrix_layout, int m, int n, int k, IntPtr A, int lda, IntPtr tau);
		#region QR factorization
		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_sgeqrf(MklSolverLayout matrix_layout, int m, int n, IntPtr a, int lda, IntPtr tau);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_dgeqrf(MklSolverLayout matrix_layout, int m, int n, IntPtr a, int lda, IntPtr tau);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_cgeqrf(MklSolverLayout matrix_layout, int m, int n, IntPtr a, int lda, IntPtr tau);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_zgeqrf(MklSolverLayout matrix_layout, int m, int n, IntPtr a, int lda, IntPtr tau);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_sorgqr(MklSolverLayout matrix_layout, int m, int n, int k, IntPtr a, int lda, [In] IntPtr tau);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_dorgqr(MklSolverLayout matrix_layout, int m, int n, int k, IntPtr a, int lda, [In] IntPtr tau);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_cungqr(MklSolverLayout matrix_layout, int m, int n, int k, IntPtr a, int lda, [In] IntPtr tau);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_zungqr(MklSolverLayout matrix_layout, int m, int n, int k, IntPtr a, int lda, [In] IntPtr tau);
		#endregion


		/// <summary>
		/// This function computes the all eigenvalues and, optionally, all eigenvectors of a matrix.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix <paramref name="A"/></param>
		/// <param name="jobz">specifies options to either compute eigenvalue only or compute eigen-pair.</param>
		/// <param name="uplo">specifies which part of <paramref name="A"/> is stored.</param>
		/// <param name="n">number of rows and columns of matrix <paramref name="A"/></param>
		/// <param name="A">matrix of dimension <paramref name="lda"/>×<paramref name="n"/>, will be overwritten as the result eigenvectors</param>
		/// <param name="lda">leading dimension of two-dimensional array used to store matrix <paramref name="A"/></param>
		/// <param name="w">pre-allocated array of dimension at least size <paramref name="n"/>, contains the result eigenvalues</param>
		/// <returns>The info. If <c>info = 0</c>, the process is successful. if <c>info = -i</c>, the i-th parameter is wrong. If <c>info = i</c>, and <c>jobz = 'N'</c>, then the algorithm failed to converge; i indicates the number of off-diagonal elements of an intermediate tridiagonal form which did not converge to zero. If <c>info = i</c>, and <c>jobz = 'V'</c>, then the algorithm failed to compute an eigenvalue while working on the sub-matrix lying in rows and columns <c>info/(n+1)</c> through <c>mod(info, n+1)</c>.</returns>
		internal delegate int syevdFunc(MklSolverLayout matrix_layout, sbyte jobz, sbyte uplo, int n, IntPtr A, int lda, IntPtr w);
		#region symmetric Hermitian eigen
		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_ssyevd(MklSolverLayout matrix_layout, sbyte jobz, sbyte uplo, int n, IntPtr A, int lda, IntPtr w);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_dsyevd(MklSolverLayout matrix_layout, sbyte jobz, sbyte uplo, int n, IntPtr A, int lda, IntPtr w);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_cheevd(MklSolverLayout matrix_layout, sbyte jobz, sbyte uplo, int n, IntPtr A, int lda, IntPtr w);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_zheevd(MklSolverLayout matrix_layout, sbyte jobz, sbyte uplo, int n, IntPtr A, int lda, IntPtr w);
		#endregion


		/// <summary>
		/// Computes the eigenvalues and left and right eigenvectors of a general matrix <paramref name="A"/>.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix <paramref name="A"/>.</param>
		/// <param name="jobvl">specifies options to compute left eigenvectors or not.</param>
		/// <param name="jobvr">specifies options to compute right eigenvectors or not.</param>
		/// <param name="n">number of rows and columns of matrix <paramref name="A"/></param>
		/// <param name="A">matrix of dimension <paramref name="lda"/>×<paramref name="n"/></param>
		/// <param name="lda">leading dimension of two-dimensional array used to store matrix <paramref name="A"/></param>
		/// <param name="wr">pre-allocated array of dimension at least size <paramref name="n"/>, contains the result eigenvalues' real parts</param>
		/// <param name="wi">pre-allocated array of dimension at least size <paramref name="n"/>, contains the result eigenvalues' imaginary parts</param>
		/// <param name="Vl">pre-allocated array of dimension at least size <paramref name="ldvl"/>×<paramref name="n"/>, contains the result left eigenvectors</param>
		/// <param name="ldvl">leading dimension of matrix <paramref name="Vl"/></param>
		/// <param name="Vr">pre-allocated array of dimension at least size <paramref name="ldvr"/>×<paramref name="n"/>, contains the result right eigenvectors</param>
		/// <param name="ldvr">leading dimension of matrix <paramref name="Vr"/></param>
		/// <returns>The info. If <c>info == 0</c>, the operation is successful; if <c>info == -i</c>, the <c>i</c><sup>th</sup> parameter is wrong (not counting handle).<br/>
		/// If <c>info ≤ <paramref name="n"/></c>, the QR algorithm failed to compute all the eigenvalues; <paramref name="wr"/> and <paramref name="wi"/> contain those eigenvalues which have converged</returns>
		internal delegate int geevRealFunc(MklSolverLayout matrix_layout, sbyte jobvl, sbyte jobvr, int n, IntPtr A, int lda, IntPtr wr, IntPtr wi, IntPtr Vl, int ldvl, IntPtr Vr, int ldvr);

		/// <summary>
		/// Computes the eigenvalues and left and right eigenvectors of a general matrix <paramref name="A"/>.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix <paramref name="A"/>.</param>
		/// <param name="jobvl">specifies options to compute left eigenvectors or not.</param>
		/// <param name="jobvr">specifies options to compute right eigenvectors or not.</param>
		/// <param name="n">number of rows and columns of matrix <paramref name="A"/></param>
		/// <param name="A">matrix of dimension <paramref name="lda"/>×<paramref name="n"/></param>
		/// <param name="lda">leading dimension of two-dimensional array used to store matrix <paramref name="A"/></param>
		/// <param name="w">pre-allocated array of dimension at least size <paramref name="n"/>, contains the result eigenvalues</param>
		/// <param name="Vl">pre-allocated array of dimension at least size <paramref name="ldvl"/>×<paramref name="n"/>, contains the result left eigenvectors</param>
		/// <param name="ldvl">leading dimension of matrix <paramref name="Vl"/></param>
		/// <param name="Vr">pre-allocated array of dimension at least size <paramref name="ldvr"/>×<paramref name="n"/>, contains the result right eigenvectors</param>
		/// <param name="ldvr">leading dimension of matrix <paramref name="Vr"/></param>
		/// <returns>The info. If <c>info == 0</c>, the operation is successful; if <c>info == -i</c>, the <c>i</c><sup>th</sup> parameter is wrong (not counting handle).<br/>
		/// If <c>info ≤ <paramref name="n"/></c>, the QR algorithm failed to compute all the eigenvalues; <paramref name="w"/> contains those eigenvalues which have converged</returns>
		internal delegate int geevCompFunc(MklSolverLayout matrix_layout, sbyte jobvl, sbyte jobvr, int n, IntPtr A, int lda, IntPtr w, IntPtr Vl, int ldvl, IntPtr Vr, int ldvr);
		#region non-symmetric eigen
		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_sgeev(MklSolverLayout matrix_layout, sbyte jobvl, sbyte jobvr, int n, IntPtr A, int lda, IntPtr wr, IntPtr wi, IntPtr Vl, int ldvl, IntPtr Vr, int ldvr);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_dgeev(MklSolverLayout matrix_layout, sbyte jobvl, sbyte jobvr, int n, IntPtr A, int lda, IntPtr wr, IntPtr wi, IntPtr Vl, int ldvl, IntPtr Vr, int ldvr);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_cgeev(MklSolverLayout matrix_layout, sbyte jobvl, sbyte jobvr, int n, IntPtr A, int lda, IntPtr w, IntPtr Vl, int ldvl, IntPtr Vr, int ldvr);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_zgeev(MklSolverLayout matrix_layout, sbyte jobvl, sbyte jobvr, int n, IntPtr A, int lda, IntPtr w, IntPtr Vl, int ldvl, IntPtr Vr, int ldvr);
		#endregion


		/// <summary>
		/// This function computes the singular value decomposition (SVD) of a matrix <paramref name="A"/> and corresponding the left and/or right singular vectors.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix <paramref name="A"/></param>
		/// <param name="jobu">specifies options for computing all or part of the matrix <paramref name="U"/>:
		/// <list type="bullet">
		/// <item><description>'A' → All <paramref name="m"/> columns are stored</description></item>
		/// <item><description>'S' → The first <c>min(<paramref name="m"/>, <paramref name="n"/>)</c> columns are stored</description></item>
		/// <item><description>'O' → The first <c>min(<paramref name="m"/>, <paramref name="n"/>)</c> columns are overwritten in <paramref name="A"/></description></item>
		/// <item><description>'N' → None of the columns are stored</description></item>
		/// </list>
		/// </param>
		/// <param name="jobvt">specifies options for computing all or part of the matrix <paramref name="Vt"/>, same as <paramref name="jobu"/>, but for rows rather than columns</param>
		/// <param name="m">number of rows of matrix</param>
		/// <param name="n">number of columns of matrix</param>
		/// <param name="A">matrix with size <paramref name="m"/>×<paramref name="n"/> and leading dimension <paramref name="lda"/></param>
		/// <param name="lda">leading dimension of <paramref name="A"/></param>
		/// <param name="S">output singular values of size <c>min(<paramref name="m"/>, <paramref name="n"/>)</c>, must be pre-allocated and of corresponding real type</param>
		/// <param name="U">left unitary matrix with size <paramref name="ldu"/>×<paramref name="m"/>, must be pre-allocated</param>
		/// <param name="ldu">leading dimension of <paramref name="U"/></param>
		/// <param name="Vt">left unitary matrix with size <paramref name="ldvt"/>×<paramref name="n"/>, must be pre-allocated</param>
		/// <param name="ldvt">leading dimension of <paramref name="Vt"/></param>
		/// <param name="superb">If <c>bdsqr</c> does not converge (indicated by the return value <c>info &gt; 0</c>), on exit <c>superb(0:min(m,n)-2)</c> contains the unconverged super-diagonal elements of an upper bidiagonal matrix <c>B</c> whose diagonal is in <paramref name="S"/> (not necessarily sorted). <c>B</c> satisfies <c><paramref name="A"/> = <paramref name="U"/> * B * <paramref name="Vt"/></c>, so it has the same singular values as <paramref name="A"/>, and singular vectors related by <paramref name="U"/> and <paramref name="Vt"/>.</param>
		/// <returns>The info. If <c>info == 0</c>, the operation is successful; if <c>info == -i</c>, the <c>i</c><sup>th</sup> parameter is wrong (not counting handle); if <c>info &gt; 0</c>, it indicates how many super-diagonals of an intermediate bidiagonal form did not converge to zero.</returns>
		internal delegate int svdFunc(MklSolverLayout matrix_layout, sbyte jobu, sbyte jobvt, int m, int n, IntPtr A, int lda, IntPtr S, IntPtr U, int ldu, IntPtr Vt, int ldvt, IntPtr superb);
		#region SVD
		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_sgesvd(MklSolverLayout matrix_layout, sbyte jobu, sbyte jobvt, int m, int n, IntPtr A, int lda, IntPtr S, IntPtr U, int ldu, IntPtr Vt, int ldvt, IntPtr superb);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_dgesvd(MklSolverLayout matrix_layout, sbyte jobu, sbyte jobvt, int m, int n, IntPtr A, int lda, IntPtr S, IntPtr U, int ldu, IntPtr Vt, int ldvt, IntPtr superb);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_cgesvd(MklSolverLayout matrix_layout, sbyte jobu, sbyte jobvt, int m, int n, IntPtr A, int lda, IntPtr S, IntPtr U, int ldu, IntPtr Vt, int ldvt, IntPtr superb);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_zgesvd(MklSolverLayout matrix_layout, sbyte jobu, sbyte jobvt, int m, int n, IntPtr A, int lda, IntPtr S, IntPtr U, int ldu, IntPtr Vt, int ldvt, IntPtr superb);
		#endregion



		/// <summary>
		/// Computes the eigenvalues and real Schur factorization of a general matrix, and orders the factorization so that selected eigenvalues are at the top left of the Schur form.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix <paramref name="A"/></param>
		/// <param name="jobv">specifies options for computing all ('V') or none ('N') of the unitary matrix</param>
		/// <param name="sort">specifies options for using <paramref name="selectFunc"/> to select and order eigenvalues or not</param>
		/// <param name="selectFunc">the selection callback function whose inputs are real and imaginary parts of eigenvalue, returns the order as <see cref="int"/>, 0 means do not select</param>
		/// <param name="n">number of columns and rows of matrix <paramref name="A"/></param>
		/// <param name="A">matrix with size <paramref name="n"/>×<paramref name="n"/> and leading dimension <paramref name="lda"/></param>
		/// <param name="lda">leading dimension of <paramref name="A"/></param>
		/// <param name="sdim">output number of selected eigenvalues</param>
		/// <param name="wr">output real parts of eigenvalues</param>
		/// <param name="wi">output imaginary parts of eigenvalues</param>
		/// <param name="V">output unitary matrix with size <paramref name="n"/>×<paramref name="n"/> and leading dimension <paramref name="ldv"/></param>
		/// <param name="ldv">leading dimension of <paramref name="V"/></param>
		/// <returns>The info. If <c>info == 0</c>, the operation is successful; if <c>info == -i</c>, the <c>i</c><sup>th</sup> parameter is wrong (not counting handle).<br/>
		/// If <c>info ≤ <paramref name="n"/></c>, the QR algorithm failed to compute all the eigenvalues; <paramref name="wr"/> and <paramref name="wi"/> contain those eigenvalues which have converged; if <paramref name="jobv"/> is 'V', <paramref name="V"/> contains the matrix which reduces <paramref name="A"/> to its partially converged Schur form.<br/>
		/// If <c>info ≤ <paramref name="n"/>+1</c>, the eigenvalues could not be reordered because some eigenvalues were too close to separate (the problem is very ill-conditioned).<br/>
		/// If <c>info ≤ <paramref name="n"/>+2</c>, after reordering, round-off changed values of some complex eigenvalues so that leading eigenvalues in the Schur form no longer satisfy <c><paramref name="selectFunc"/> ≠ 0</c>; this could also be caused by underflow due to scaling.</returns>
		internal delegate int realSchurFunc<T>(MklSolverLayout matrix_layout, sbyte jobv, sbyte sort, schurCallbackReal<T> selectFunc, int n, IntPtr A, int lda, ref int sdim, T[] wr, T[] wi, IntPtr V, int ldv);

		/// <summary>
		/// Computes the eigenvalues and real Schur factorization of a general matrix, and orders the factorization so that selected eigenvalues are at the top left of the Schur form.
		/// </summary>
		/// <param name="matrix_layout"><see cref="MklSolverLayout"/> of matrix <paramref name="A"/></param>
		/// <param name="jobv">specifies options for computing all ('V') or none ('N') of the unitary matrix</param>
		/// <param name="sort">specifies options for using <paramref name="selectFunc"/> to select and order eigenvalues or not</param>
		/// <param name="selectFunc">the selection callback function whose input is the eigenvalue, returns the order as <see cref="int"/>, 0 means do not select</param>
		/// <param name="n">number of columns and rows of matrix <paramref name="A"/></param>
		/// <param name="A">matrix with size <paramref name="n"/>×<paramref name="n"/> and leading dimension <paramref name="lda"/></param>
		/// <param name="lda">leading dimension of <paramref name="A"/></param>
		/// <param name="sdim">output number of selected eigenvalues</param>
		/// <param name="w">output eigenvalues</param>
		/// <param name="V">output unitary matrix with size <paramref name="n"/>×<paramref name="n"/> and leading dimension <paramref name="ldv"/></param>
		/// <param name="ldv">leading dimension of <paramref name="V"/></param>
		/// <returns>The info. If <c>info == 0</c>, the operation is successful; if <c>info == -i</c>, the <c>i</c><sup>th</sup> parameter is wrong (not counting handle).<br/>
		/// If <c>info ≤ <paramref name="n"/></c>, the QR algorithm failed to compute all the eigenvalues; <paramref name="w"/> contain those eigenvalues which have converged; if <paramref name="jobv"/> is 'V', <paramref name="V"/> contains the matrix which reduces <paramref name="A"/> to its partially converged Schur form.<br/>
		/// If <c>info ≤ <paramref name="n"/>+1</c>, the eigenvalues could not be reordered because some eigenvalues were too close to separate (the problem is very ill-conditioned).<br/>
		/// If <c>info ≤ <paramref name="n"/>+2</c>, after reordering, round-off changed values of some complex eigenvalues so that leading eigenvalues in the Schur form no longer satisfy <c><paramref name="selectFunc"/> ≠ 0</c>; this could also be caused by underflow due to scaling.</returns>
		internal delegate int compSchurFunc<T>(MklSolverLayout matrix_layout, sbyte jobv, sbyte sort, schurCallbackComp<T> selectFunc, int n, IntPtr A, int lda, ref int sdim, T[] w, IntPtr V, int ldv);
		#region Schur
		internal delegate int schurCallbackReal<T>(ref T re, ref T im);
		internal delegate int schurCallbackComp<T>(ref T v);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_sgees(MklSolverLayout matrix_layout, sbyte jobv, sbyte sort, [MarshalAs(UnmanagedType.FunctionPtr)] schurCallbackReal<float> selectFunc, int n, IntPtr A, int lda, ref int sdim, float[] wr, float[] wi, IntPtr V, int ldv);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_dgees(MklSolverLayout matrix_layout, sbyte jobv, sbyte sort, [MarshalAs(UnmanagedType.FunctionPtr)] schurCallbackReal<double> selectFunc, int n, IntPtr A, int lda, ref int sdim, double[] wr, double[] wi, IntPtr V, int ldv);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_cgees(MklSolverLayout matrix_layout, sbyte jobv, sbyte sort, [MarshalAs(UnmanagedType.FunctionPtr)] schurCallbackComp<FloatComplex> selectFunc, int n, IntPtr A, int lda, ref int sdim, FloatComplex[] w, IntPtr V, int ldv);

		[DllImport(MKLBLAS_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern int LAPACKE_zgees(MklSolverLayout matrix_layout, sbyte jobv, sbyte sort, [MarshalAs(UnmanagedType.FunctionPtr)] schurCallbackComp<DoubleComplex> selectFunc, int n, IntPtr A, int lda, ref int sdim, DoubleComplex[] w, IntPtr V, int ldv);
		#endregion
	}
}
