//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Althea.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Parameter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parameter() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Althea.Resources.Parameter", typeof(Parameter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameters cannot be null at the same time. 的本地化字符串。
        /// </summary>
        public static string CannotAllNull {
            get {
                return ResourceManager.GetString("CannotAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter cannot be less than zero. 的本地化字符串。
        /// </summary>
        public static string CannotNegative {
            get {
                return ResourceManager.GetString("CannotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter cannot be larger than zero. 的本地化字符串。
        /// </summary>
        public static string CannotPositive {
            get {
                return ResourceManager.GetString("CannotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter cannot be zero. 的本地化字符串。
        /// </summary>
        public static string CannotZero {
            get {
                return ResourceManager.GetString("CannotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter contains duplicate indices which is not allowed. 的本地化字符串。
        /// </summary>
        public static string DuplicateIndices {
            get {
                return ResourceManager.GetString("DuplicateIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter contains duplicate values, which is not allowed. 的本地化字符串。
        /// </summary>
        public static string DuplicateValue {
            get {
                return ResourceManager.GetString("DuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given enum parameter must be a bit flag. 的本地化字符串。
        /// </summary>
        public static string EnumNotFlag {
            get {
                return ResourceManager.GetString("EnumNotFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter has invalid value. 的本地化字符串。
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter cannot be larger than or equal to zero. 的本地化字符串。
        /// </summary>
        public static string MustNegative {
            get {
                return ResourceManager.GetString("MustNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter cannot be less than or equal to zero. 的本地化字符串。
        /// </summary>
        public static string MustPositive {
            get {
                return ResourceManager.GetString("MustPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameters have different size, which is not allowed. 的本地化字符串。
        /// </summary>
        public static string NotSameSize {
            get {
                return ResourceManager.GetString("NotSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter is of an unexpected type. 的本地化字符串。
        /// </summary>
        public static string UnexpectedType {
            get {
                return ResourceManager.GetString("UnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter contains unexpected value(s). 的本地化字符串。
        /// </summary>
        public static string UnexpectedValue {
            get {
                return ResourceManager.GetString("UnexpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter has incompatible size. 的本地化字符串。
        /// </summary>
        public static string WrongSize {
            get {
                return ResourceManager.GetString("WrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given parameter has size of zero which is not allowed. 的本地化字符串。
        /// </summary>
        public static string ZeroSize {
            get {
                return ResourceManager.GetString("ZeroSize", resourceCulture);
            }
        }
    }
}
