// NOTICE:
// This file is generated by corresponding ".tt" file template, do NOT modify this file.

using System;

using Althea.Linq;
using Althea.Helpers;
using Althea.NativeTypes;
using Althea.Resources;


namespace Althea.TensorAlgebra
{
	public readonly ref partial struct TensorOrder
	{
		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7, OrderElement a8) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}

			// add a8
			if (order.AsSpan(n).Contains(elements.a8.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a8.main;
			if (elements.a8.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a8.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a8.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7, OrderElement a8, OrderElement a9) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}

			// add a8
			if (order.AsSpan(n).Contains(elements.a8.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a8.main;
			if (elements.a8.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a8.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a8.auxi;
			}

			// add a9
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a9.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a9.main;
			if (elements.a9.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a9.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a9.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7, OrderElement a8, OrderElement a9, OrderElement a10) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}

			// add a8
			if (order.AsSpan(n).Contains(elements.a8.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a8.main;
			if (elements.a8.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a8.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a8.auxi;
			}

			// add a9
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a9.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a9.main;
			if (elements.a9.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a9.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a9.auxi;
			}

			// add a10
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a10.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a10.main;
			if (elements.a10.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a10.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a10.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7, OrderElement a8, OrderElement a9, OrderElement a10, OrderElement a11) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}

			// add a8
			if (order.AsSpan(n).Contains(elements.a8.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a8.main;
			if (elements.a8.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a8.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a8.auxi;
			}

			// add a9
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a9.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a9.main;
			if (elements.a9.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a9.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a9.auxi;
			}

			// add a10
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a10.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a10.main;
			if (elements.a10.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a10.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a10.auxi;
			}

			// add a11
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a11.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a11.main;
			if (elements.a11.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a11.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a11.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7, OrderElement a8, OrderElement a9, OrderElement a10, OrderElement a11, OrderElement a12) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}

			// add a8
			if (order.AsSpan(n).Contains(elements.a8.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a8.main;
			if (elements.a8.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a8.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a8.auxi;
			}

			// add a9
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a9.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a9.main;
			if (elements.a9.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a9.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a9.auxi;
			}

			// add a10
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a10.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a10.main;
			if (elements.a10.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a10.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a10.auxi;
			}

			// add a11
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a11.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a11.main;
			if (elements.a11.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a11.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a11.auxi;
			}

			// add a12
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a12.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a12.main;
			if (elements.a12.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a12.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a12.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7, OrderElement a8, OrderElement a9, OrderElement a10, OrderElement a11, OrderElement a12, OrderElement a13) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}

			// add a8
			if (order.AsSpan(n).Contains(elements.a8.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a8.main;
			if (elements.a8.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a8.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a8.auxi;
			}

			// add a9
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a9.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a9.main;
			if (elements.a9.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a9.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a9.auxi;
			}

			// add a10
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a10.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a10.main;
			if (elements.a10.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a10.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a10.auxi;
			}

			// add a11
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a11.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a11.main;
			if (elements.a11.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a11.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a11.auxi;
			}

			// add a12
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a12.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a12.main;
			if (elements.a12.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a12.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a12.auxi;
			}

			// add a13
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a13.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a13.main;
			if (elements.a13.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a13.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a13.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7, OrderElement a8, OrderElement a9, OrderElement a10, OrderElement a11, OrderElement a12, OrderElement a13, OrderElement a14) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}

			// add a8
			if (order.AsSpan(n).Contains(elements.a8.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a8.main;
			if (elements.a8.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a8.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a8.auxi;
			}

			// add a9
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a9.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a9.main;
			if (elements.a9.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a9.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a9.auxi;
			}

			// add a10
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a10.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a10.main;
			if (elements.a10.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a10.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a10.auxi;
			}

			// add a11
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a11.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a11.main;
			if (elements.a11.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a11.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a11.auxi;
			}

			// add a12
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a12.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a12.main;
			if (elements.a12.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a12.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a12.auxi;
			}

			// add a13
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a13.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a13.main;
			if (elements.a13.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a13.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a13.auxi;
			}

			// add a14
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a14.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a14.main;
			if (elements.a14.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a14.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a14.auxi;
			}
			return new(order);
		}

		/// <summary>
		/// Create a new <see cref="TensorOrder"/> with given <see cref="OrderElement"/>s as the order.
		/// </summary>
		/// <param name="elements">The input tuple of <see cref="OrderElement"/>s</param>
		/// <returns>The created <see cref="TensorOrder"/> from given <see cref="OrderElement"/>s.</returns>
		/// <exception cref="ArgumentException">If the <see cref="OrderElement"/>s imply duplicate indices</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the parameter &lt; 0 or ≥ max_rank</exception>
		/// <exception cref="NotSupportedException">If the total size &gt; max_rank</exception>
		public static implicit operator TensorOrder((OrderElement a0, OrderElement a1, OrderElement a2, OrderElement a3, OrderElement a4, OrderElement a5, OrderElement a6, OrderElement a7, OrderElement a8, OrderElement a9, OrderElement a10, OrderElement a11, OrderElement a12, OrderElement a13, OrderElement a14, OrderElement a15) elements)
		{
			FixedBuffer_64<Union> order = default;
			byte n = 0;

			// add a0
			order[n++] = elements.a0.main;
			if (elements.a0.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a0.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a0.auxi;
			}

			// add a1
			if (order.AsSpan(n).Contains(elements.a1.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a1.main;
			if (elements.a1.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a1.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a1.auxi;
			}

			// add a2
			if (order.AsSpan(n).Contains(elements.a2.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a2.main;
			if (elements.a2.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a2.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a2.auxi;
			}

			// add a3
			if (order.AsSpan(n).Contains(elements.a3.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a3.main;
			if (elements.a3.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a3.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a3.auxi;
			}

			// add a4
			if (order.AsSpan(n).Contains(elements.a4.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a4.main;
			if (elements.a4.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a4.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a4.auxi;
			}

			// add a5
			if (order.AsSpan(n).Contains(elements.a5.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a5.main;
			if (elements.a5.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a5.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a5.auxi;
			}

			// add a6
			if (order.AsSpan(n).Contains(elements.a6.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a6.main;
			if (elements.a6.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a6.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a6.auxi;
			}

			// add a7
			if (order.AsSpan(n).Contains(elements.a7.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a7.main;
			if (elements.a7.auxi != default)
			{
				if (order.AsSpan(n).Contains(elements.a7.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a7.auxi;
			}

			// add a8
			if (order.AsSpan(n).Contains(elements.a8.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a8.main;
			if (elements.a8.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a8.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a8.auxi;
			}

			// add a9
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a9.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a9.main;
			if (elements.a9.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a9.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a9.auxi;
			}

			// add a10
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a10.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a10.main;
			if (elements.a10.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a10.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a10.auxi;
			}

			// add a11
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a11.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a11.main;
			if (elements.a11.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a11.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a11.auxi;
			}

			// add a12
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a12.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a12.main;
			if (elements.a12.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a12.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a12.auxi;
			}

			// add a13
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a13.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a13.main;
			if (elements.a13.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a13.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a13.auxi;
			}

			// add a14
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a14.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a14.main;
			if (elements.a14.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a14.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a14.auxi;
			}

			// add a15
			if (n >= MAX_RANK)
				throw new NotSupportedException();
			if (order.AsSpan(n).Contains(elements.a15.main))
				throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
			order[n++] = elements.a15.main;
			if (elements.a15.auxi != default)
			{
				if (n >= MAX_RANK)
					throw new NotSupportedException();
				if (order.AsSpan(n).Contains(elements.a15.auxi))
					throw new ArgumentException(Parameter.DuplicateIndices, nameof(elements));
				order[n++] = elements.a15.auxi;
			}
			return new(order);
		}

	}
}