<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <EnablePreviewFeatures>True</EnablePreviewFeatures>
    <LangVersion>preview</LangVersion>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <DocumentationMarkdown>$(MSBuildProjectDirectory)\documents\$(MSBuildProjectName).md</DocumentationMarkdown>
    <Win32Resource />
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <RootNamespace>Althea</RootNamespace>
    <AssemblyName>Althea</AssemblyName>
    <AnalysisLevel>latest</AnalysisLevel>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.Experimental" Version="6.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Platform)' == 'x64' ">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <DocumentationFile>$(MSBuildProjectDirectory)\documents\$(MSBuildProjectName).xml</DocumentationFile>
    <NoWarn>1701;1702</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DocumentationFile>$(MSBuildProjectDirectory)\documents\$(MSBuildProjectName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Helpers\FixedClassBuffer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FixedClassBuffer.tt</DependentUpon>
    </Compile>
    <Compile Update="Helpers\FixedUnmanagedBuffer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FixedUnmanagedBuffer.tt</DependentUpon>
    </Compile>
    <Compile Update="Helpers\SwapSort.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SwapSort.tt</DependentUpon>
    </Compile>
    <Compile Update="Resources\Exception.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Exception.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Other.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Other.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Backend.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Backend.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Parameter.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Parameter.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Print.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Print.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Support.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Support.resx</DependentUpon>
    </Compile>
    <Compile Update="Storage\MixedStorage.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MixedStorage.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Exception.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Exception.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Other.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Other.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Backend.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Backend.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Parameter.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Parameter.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Print.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Print.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Support.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Support.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Althea.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\FixedClassBuffer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FixedClassBuffer.cs</LastGenOutput>
    </None>
    <None Update="Helpers\FixedUnmanagedBuffer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FixedUnmanagedBuffer.cs</LastGenOutput>
    </None>
    <None Update="Helpers\SwapSort.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SwapSort.cs</LastGenOutput>
    </None>
    <None Update="Storage\MixedStorage.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MixedStorage.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="documents\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Althea.SourceGenerator\Althea.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
