<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <EnablePreviewFeatures>True</EnablePreviewFeatures>
    <LangVersion>preview</LangVersion>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="documents\" />
  </ItemGroup>

  <PropertyGroup>
    <DocumentationMarkdown>$(MSBuildProjectDirectory)\documents\$(MSBuildProjectName).md</DocumentationMarkdown>
    <Win32Resource />
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <RootNamespace>Althea</RootNamespace>
    <AssemblyName>Althea</AssemblyName>
    <AnalysisLevel>latest</AnalysisLevel>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.Experimental" Version="6.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Platform)' == 'x64' ">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
    <DocumentationFile>$(MSBuildProjectDirectory)\documents\$(MSBuildProjectName).xml</DocumentationFile>
    <NoWarn>1701;1702</NoWarn>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <DocumentationFile>$(MSBuildProjectDirectory)\documents\$(MSBuildProjectName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Helpers\FixedClassBuffer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FixedClassBuffer.tt</DependentUpon>
    </Compile>
    <Compile Update="Helpers\FixedUnmanagedBuffer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FixedUnmanagedBuffer.tt</DependentUpon>
    </Compile>
    <Compile Update="Helpers\SwapSort.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SwapSort.tt</DependentUpon>
    </Compile>
    <Compile Update="Random\API.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>API.tt</DependentUpon>
    </Compile>
    <Compile Update="Resources\ArithmeticError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ArithmeticError.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\OtherError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OtherError.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\FileError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FileError.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\BackendError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BackendError.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ParameterError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ParameterError.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Print.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Print.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SparseError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SparseError.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\StorageError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>StorageError.resx</DependentUpon>
    </Compile>
    <Compile Update="Storage\MixedStorage.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MixedStorage.tt</DependentUpon>
    </Compile>
    <Compile Update="TensorAlgebra\TensorOrderCreate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TensorOrderCreate.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ArithmeticError.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ArithmeticError.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\OtherError.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>OtherError.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\FileError.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FileError.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\BackendError.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>BackendError.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ParameterError.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ParameterError.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Print.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Print.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SparseError.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SparseError.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\StorageError.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>StorageError.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Althea.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\FixedClassBuffer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FixedClassBuffer.cs</LastGenOutput>
    </None>
    <None Update="Helpers\FixedUnmanagedBuffer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FixedUnmanagedBuffer.cs</LastGenOutput>
    </None>
    <None Update="Helpers\SwapSort.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SwapSort.cs</LastGenOutput>
    </None>
    <None Update="Random\API.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>API.cs</LastGenOutput>
    </None>
    <None Update="Storage\MixedStorage.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MixedStorage.cs</LastGenOutput>
    </None>
    <None Update="TensorAlgebra\TensorOrderCreate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>TensorOrderCreate.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="Random\API.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>API.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Althea.SourceGenerator\Althea.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
