using System;


namespace Althea.Rng
{
	/// <summary>
	/// The random generator routine interface
	/// </summary>
	public interface IRand : IDisposable
	{
		/// <summary>
		/// Set seed of this random generator
		/// </summary>
		/// <param name="seed">The seed</param>
		void SetSeed(long seed);

		/// <summary>
		/// Fill an array with generated random 32-bit integers (<see cref="int"/>), each bit random.
		/// </summary>
		/// <param name="arr">The array to fill</param>
		/// <param name="length">The length of the array</param>
		void GenerateInt(IntPtr arr, long length);

		/// <summary>
		/// Fill an array with generated random <see cref="float"/>s in range [0.0f, 1.0f).
		/// </summary>
		/// <param name="arr">The array to fill</param>
		/// <param name="length">The length of the array</param>
		void GenerateSingle(IntPtr arr, long length);

		/// <summary>
		/// Fill an array with generated random <see cref="double"/>s in range [0.0d, 1.0d).
		/// </summary>
		/// <param name="arr">The array to fill</param>
		/// <param name="length">The length of the array</param>
		void GenerateDouble(IntPtr arr, long length);
	}
}


namespace Althea.Rng.Cuda
{
	internal sealed class CudaRand : IRand
	{
		#region base
		private readonly IntPtr handle;

		public CudaRand()
		{
			this.handle = new IntPtr();
			NativeMethods.curandCreateGenerator(ref this.handle, GeneratorType.PseudoDefault).Check();
			NativeMethods.curandSetGeneratorOrdering(this.handle, Ordering.PseudoBest).Check();
			this.SetSeed(new Random().Next());
		}

		/// <summary>
		/// The finalize method invoked by the GC
		/// </summary>
		~CudaRand()
		{
			Dispose();
		}

		public void Dispose()
		{
			NativeMethods.curandDestroyGenerator(this.handle).Check();
			GC.SuppressFinalize(this);
		}
		#endregion

		#region generate
		public void GenerateDouble(IntPtr arr, long length)
		{
			NativeMethods.curandGenerateUniformDouble(this.handle, arr, length).Check();
		}

		public void GenerateInt(IntPtr arr, long length)
		{
			NativeMethods.curandGenerate(this.handle, arr, length).Check();
		}

		public void GenerateSingle(IntPtr arr, long length)
		{
			NativeMethods.curandGenerateUniform(this.handle, arr, length).Check();
		}
		#endregion

		#region supplement
		/// <summary>
		/// Set seed of random generator.
		/// </summary>
		/// <param name="seed">The <see cref="long"/> seed to set</param>
		public void SetSeed(long seed)
		{
			NativeMethods.curandSetPseudoRandomGeneratorSeed(this.handle, seed).Check();
		}

		/// <summary>
		/// Set the absolute offset of the pseudo or quasi-random number generator. All values of offset are valid.
		/// <br/>The offset position is absolute, not relative to the current position in the sequence.
		/// </summary>
		/// <param name="offset">The <see cref="long"/> offset to set</param>
		/// <exception cref="StatusException">if the returned status is not success</exception>
		public void SetOffset(long offset)
		{
			NativeMethods.curandSetGeneratorOffset(this.handle, offset).Check();
		}

		/// <summary>
		/// Set the ordering of results of the pseudo or quasi-random number generator.
		/// </summary>
		/// <param name="order">Legal values of order for pseudo-random generators are:<br/>
		/// <list type="bullet">
		/// <item>
		/// <description><see cref="Ordering.PseudoDefault"/></description>
		/// </item>
		/// <item>
		/// <description><see cref="Ordering.PseudoBest"/></description>
		/// </item>
		/// <item>
		/// <description><see cref="Ordering.Pseudoeseded"/></description>
		/// </item>
		/// </list>
		/// Legal values of order for quasi-random generators is <see cref="Ordering.QuasiDefault"/></param>
		/// <exception cref="StatusException">if the returned status is not success</exception>
		public void SetOrder(Ordering order)
		{
			NativeMethods.curandSetGeneratorOrdering(this.handle, order).Check();
		}

		/// <summary>
		/// Set the number of dimensions to be generated by the quasi-random number generator. Legal values for <paramref name="dimensions"/> are 1 to 20000.
		/// </summary>
		/// <param name="dimensions">number of dimensions</param>
		/// <exception cref="StatusException">if the returned status is not success</exception>
		public void SetDimensions(int dimensions)
		{
			NativeMethods.curandSetQuasiRandomGeneratorDimensions(this.handle, dimensions).Check();
		}
		#endregion
	}
}


namespace Althea.Rng.Mkl
{
	internal sealed class MklRand : IRand
	{
		#region base
		private IntPtr streamDouble, streamSingle, streamInt;

		public MklRand()
		{
			Initialize();
		}

		/// <summary>
		/// The finalize method invoked by the GC
		/// </summary>
		~MklRand()
		{
			Dispose();
		}

		private void Initialize(int? seed = null)
		{
			seed ??= (new Random().Next());
			NativeMethods.vslNewStream(ref this.streamDouble, GeneratorType.MT19937, seed.Value).Check();
			NativeMethods.vslNewStream(ref this.streamSingle, GeneratorType.MT19937, seed.Value).Check();
			NativeMethods.vslNewStream(ref this.streamInt, GeneratorType.MT19937, seed.Value).Check();
		}

		public void Dispose()
		{
			NativeMethods.vslDeleteStream(ref this.streamDouble).Check();
			NativeMethods.vslDeleteStream(ref this.streamSingle).Check();
			NativeMethods.vslDeleteStream(ref this.streamInt).Check();
			GC.SuppressFinalize(this);
		}

		public void SetSeed(long seed)
		{
			this.Dispose();
			GC.ReRegisterForFinalize(this);
			this.Initialize(unchecked((int)seed));
		}
		#endregion

		#region generate
		public void GenerateDouble(IntPtr arr, long length)
		{
			NativeMethods.vdRngUniform(Method.Standard, this.streamDouble, checked((int)length), arr, 0, 1);
		}

		public void GenerateInt(IntPtr arr, long length)
		{
			NativeMethods.viRngUniformBits(Method.Standard, this.streamInt, checked((int)length), arr);
		}

		public void GenerateSingle(IntPtr arr, long length)
		{
			NativeMethods.vsRngUniform(Method.Standard, this.streamSingle, checked((int)length), arr, 0, 1);
		}
		#endregion
	}
}
