// NOTICE:
// This file is generated by corresponding ".tt" file template, do NOT modify this file.

using System;
using System.Runtime.CompilerServices;


namespace Althea.Helpers
{
	#region interface
	/// <summary>
	/// The interface to swap two <typeparamref name="T"/> values in-place
	/// </summary>
	/// <typeparam name="T">The type of the values to be swapped</typeparam>
	public interface ISwapper<T> where T : ISwapper<T>
	{
		/// <summary>
		/// When implemented by a derived class, swap two values <paramref name="a"/> and <paramref name="b"/> in-place
		/// </summary>
		/// <param name="a">The reference to first value to be swapped with <paramref name="b"/></param>
		/// <param name="b">The reference to second value to be swapped with <paramref name="a"/></param>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		abstract static void Swap(ref T a, ref T b);
	}

	/// <summary>
	/// The static class that provides the sort utilities for <see cref="Span{T}"/>
	/// </summary>
	public static class SwapSort
	{
		/// <summary>
		/// Sort the <paramref name="keys"/> with <paramref name="values"/> using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue">The type of the value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values">The value array as a <see cref="Span{T}"/> of <typeparamref name="TValue"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue>(this Span<TKey> keys, Span<TValue> values, Comparer<TKey>? comparer = null)
			where TValue : ISwapper<TValue> 
		{
			SortHelper<TKey, TValue>.Sort(keys, values, comparer ?? Comparer<TKey>.Default);
		}

		/// <summary>
		/// Sort the <paramref name="keys"/> with (<paramref name="values1"/><paramref name="values2"/>) using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue1">The type of the first value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue2">The type of the second value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values1">The first value array as a <see cref="Span{T}"/> of <typeparamref name="TValue1"/></param>
		/// <param name="values2">The second value array as a <see cref="Span{T}"/> of <typeparamref name="TValue2"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue1, TValue2>(this Span<TKey> keys, Span<TValue1> values1, Span<TValue2> values2, Comparer<TKey>? comparer = null)
			where TValue1 : ISwapper<TValue1> where TValue2 : ISwapper<TValue2> 
		{
			SortHelper<TKey, TValue1, TValue2>.Sort(keys, values1, values2, comparer ?? Comparer<TKey>.Default);
		}

		/// <summary>
		/// Sort the <paramref name="keys"/> with (<paramref name="values1"/><paramref name="values2"/><paramref name="values3"/>) using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue1">The type of the first value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue2">The type of the second value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue3">The type of the third value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values1">The first value array as a <see cref="Span{T}"/> of <typeparamref name="TValue1"/></param>
		/// <param name="values2">The second value array as a <see cref="Span{T}"/> of <typeparamref name="TValue2"/></param>
		/// <param name="values3">The third value array as a <see cref="Span{T}"/> of <typeparamref name="TValue3"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue1, TValue2, TValue3>(this Span<TKey> keys, Span<TValue1> values1, Span<TValue2> values2, Span<TValue3> values3, Comparer<TKey>? comparer = null)
			where TValue1 : ISwapper<TValue1> where TValue2 : ISwapper<TValue2> where TValue3 : ISwapper<TValue3> 
		{
			SortHelper<TKey, TValue1, TValue2, TValue3>.Sort(keys, values1, values2, values3, comparer ?? Comparer<TKey>.Default);
		}

		/// <summary>
		/// Sort the <paramref name="keys"/> with (<paramref name="values1"/><paramref name="values2"/><paramref name="values3"/><paramref name="values4"/>) using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue1">The type of the first value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue2">The type of the second value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue3">The type of the third value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue4">The type of the fourth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values1">The first value array as a <see cref="Span{T}"/> of <typeparamref name="TValue1"/></param>
		/// <param name="values2">The second value array as a <see cref="Span{T}"/> of <typeparamref name="TValue2"/></param>
		/// <param name="values3">The third value array as a <see cref="Span{T}"/> of <typeparamref name="TValue3"/></param>
		/// <param name="values4">The fourth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue4"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue1, TValue2, TValue3, TValue4>(this Span<TKey> keys, Span<TValue1> values1, Span<TValue2> values2, Span<TValue3> values3, Span<TValue4> values4, Comparer<TKey>? comparer = null)
			where TValue1 : ISwapper<TValue1> where TValue2 : ISwapper<TValue2> where TValue3 : ISwapper<TValue3> where TValue4 : ISwapper<TValue4> 
		{
			SortHelper<TKey, TValue1, TValue2, TValue3, TValue4>.Sort(keys, values1, values2, values3, values4, comparer ?? Comparer<TKey>.Default);
		}

		/// <summary>
		/// Sort the <paramref name="keys"/> with (<paramref name="values1"/><paramref name="values2"/><paramref name="values3"/><paramref name="values4"/><paramref name="values5"/>) using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue1">The type of the first value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue2">The type of the second value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue3">The type of the third value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue4">The type of the fourth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue5">The type of the fifth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values1">The first value array as a <see cref="Span{T}"/> of <typeparamref name="TValue1"/></param>
		/// <param name="values2">The second value array as a <see cref="Span{T}"/> of <typeparamref name="TValue2"/></param>
		/// <param name="values3">The third value array as a <see cref="Span{T}"/> of <typeparamref name="TValue3"/></param>
		/// <param name="values4">The fourth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue4"/></param>
		/// <param name="values5">The fifth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue5"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue1, TValue2, TValue3, TValue4, TValue5>(this Span<TKey> keys, Span<TValue1> values1, Span<TValue2> values2, Span<TValue3> values3, Span<TValue4> values4, Span<TValue5> values5, Comparer<TKey>? comparer = null)
			where TValue1 : ISwapper<TValue1> where TValue2 : ISwapper<TValue2> where TValue3 : ISwapper<TValue3> where TValue4 : ISwapper<TValue4> where TValue5 : ISwapper<TValue5> 
		{
			SortHelper<TKey, TValue1, TValue2, TValue3, TValue4, TValue5>.Sort(keys, values1, values2, values3, values4, values5, comparer ?? Comparer<TKey>.Default);
		}

		/// <summary>
		/// Sort the <paramref name="keys"/> with (<paramref name="values1"/><paramref name="values2"/><paramref name="values3"/><paramref name="values4"/><paramref name="values5"/><paramref name="values6"/>) using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue1">The type of the first value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue2">The type of the second value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue3">The type of the third value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue4">The type of the fourth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue5">The type of the fifth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue6">The type of the sixth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values1">The first value array as a <see cref="Span{T}"/> of <typeparamref name="TValue1"/></param>
		/// <param name="values2">The second value array as a <see cref="Span{T}"/> of <typeparamref name="TValue2"/></param>
		/// <param name="values3">The third value array as a <see cref="Span{T}"/> of <typeparamref name="TValue3"/></param>
		/// <param name="values4">The fourth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue4"/></param>
		/// <param name="values5">The fifth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue5"/></param>
		/// <param name="values6">The sixth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue6"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue1, TValue2, TValue3, TValue4, TValue5, TValue6>(this Span<TKey> keys, Span<TValue1> values1, Span<TValue2> values2, Span<TValue3> values3, Span<TValue4> values4, Span<TValue5> values5, Span<TValue6> values6, Comparer<TKey>? comparer = null)
			where TValue1 : ISwapper<TValue1> where TValue2 : ISwapper<TValue2> where TValue3 : ISwapper<TValue3> where TValue4 : ISwapper<TValue4> where TValue5 : ISwapper<TValue5> where TValue6 : ISwapper<TValue6> 
		{
			SortHelper<TKey, TValue1, TValue2, TValue3, TValue4, TValue5, TValue6>.Sort(keys, values1, values2, values3, values4, values5, values6, comparer ?? Comparer<TKey>.Default);
		}

		/// <summary>
		/// Sort the <paramref name="keys"/> with (<paramref name="values1"/><paramref name="values2"/><paramref name="values3"/><paramref name="values4"/><paramref name="values5"/><paramref name="values6"/><paramref name="values7"/>) using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue1">The type of the first value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue2">The type of the second value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue3">The type of the third value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue4">The type of the fourth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue5">The type of the fifth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue6">The type of the sixth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue7">The type of the seventh value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values1">The first value array as a <see cref="Span{T}"/> of <typeparamref name="TValue1"/></param>
		/// <param name="values2">The second value array as a <see cref="Span{T}"/> of <typeparamref name="TValue2"/></param>
		/// <param name="values3">The third value array as a <see cref="Span{T}"/> of <typeparamref name="TValue3"/></param>
		/// <param name="values4">The fourth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue4"/></param>
		/// <param name="values5">The fifth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue5"/></param>
		/// <param name="values6">The sixth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue6"/></param>
		/// <param name="values7">The seventh value array as a <see cref="Span{T}"/> of <typeparamref name="TValue7"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue1, TValue2, TValue3, TValue4, TValue5, TValue6, TValue7>(this Span<TKey> keys, Span<TValue1> values1, Span<TValue2> values2, Span<TValue3> values3, Span<TValue4> values4, Span<TValue5> values5, Span<TValue6> values6, Span<TValue7> values7, Comparer<TKey>? comparer = null)
			where TValue1 : ISwapper<TValue1> where TValue2 : ISwapper<TValue2> where TValue3 : ISwapper<TValue3> where TValue4 : ISwapper<TValue4> where TValue5 : ISwapper<TValue5> where TValue6 : ISwapper<TValue6> where TValue7 : ISwapper<TValue7> 
		{
			SortHelper<TKey, TValue1, TValue2, TValue3, TValue4, TValue5, TValue6, TValue7>.Sort(keys, values1, values2, values3, values4, values5, values6, values7, comparer ?? Comparer<TKey>.Default);
		}

		/// <summary>
		/// Sort the <paramref name="keys"/> with (<paramref name="values1"/><paramref name="values2"/><paramref name="values3"/><paramref name="values4"/><paramref name="values5"/><paramref name="values6"/><paramref name="values7"/><paramref name="values8"/>) using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue1">The type of the first value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue2">The type of the second value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue3">The type of the third value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue4">The type of the fourth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue5">The type of the fifth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue6">The type of the sixth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue7">The type of the seventh value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue8">The type of the eighth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values1">The first value array as a <see cref="Span{T}"/> of <typeparamref name="TValue1"/></param>
		/// <param name="values2">The second value array as a <see cref="Span{T}"/> of <typeparamref name="TValue2"/></param>
		/// <param name="values3">The third value array as a <see cref="Span{T}"/> of <typeparamref name="TValue3"/></param>
		/// <param name="values4">The fourth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue4"/></param>
		/// <param name="values5">The fifth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue5"/></param>
		/// <param name="values6">The sixth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue6"/></param>
		/// <param name="values7">The seventh value array as a <see cref="Span{T}"/> of <typeparamref name="TValue7"/></param>
		/// <param name="values8">The eighth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue8"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue1, TValue2, TValue3, TValue4, TValue5, TValue6, TValue7, TValue8>(this Span<TKey> keys, Span<TValue1> values1, Span<TValue2> values2, Span<TValue3> values3, Span<TValue4> values4, Span<TValue5> values5, Span<TValue6> values6, Span<TValue7> values7, Span<TValue8> values8, Comparer<TKey>? comparer = null)
			where TValue1 : ISwapper<TValue1> where TValue2 : ISwapper<TValue2> where TValue3 : ISwapper<TValue3> where TValue4 : ISwapper<TValue4> where TValue5 : ISwapper<TValue5> where TValue6 : ISwapper<TValue6> where TValue7 : ISwapper<TValue7> where TValue8 : ISwapper<TValue8> 
		{
			SortHelper<TKey, TValue1, TValue2, TValue3, TValue4, TValue5, TValue6, TValue7, TValue8>.Sort(keys, values1, values2, values3, values4, values5, values6, values7, values8, comparer ?? Comparer<TKey>.Default);
		}

		/// <summary>
		/// Sort the <paramref name="keys"/> with (<paramref name="values1"/><paramref name="values2"/><paramref name="values3"/><paramref name="values4"/><paramref name="values5"/><paramref name="values6"/><paramref name="values7"/><paramref name="values8"/><paramref name="values9"/>) using the given <typeparamref name="TKey"/> <paramref name="comparer"/>
		/// </summary>
		/// <typeparam name="TKey">The type of the keys</typeparam>
		/// <typeparam name="TValue1">The type of the first value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue2">The type of the second value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue3">The type of the third value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue4">The type of the fourth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue5">The type of the fifth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue6">The type of the sixth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue7">The type of the seventh value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue8">The type of the eighth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <typeparam name="TValue9">The type of the ninth value array which must implement <see cref="ISwapper{T}"/></typeparam>
		/// <param name="keys">The keys as a <see cref="Span{T}"/> of <typeparamref name="TKey"/></param>
		/// <param name="values1">The first value array as a <see cref="Span{T}"/> of <typeparamref name="TValue1"/></param>
		/// <param name="values2">The second value array as a <see cref="Span{T}"/> of <typeparamref name="TValue2"/></param>
		/// <param name="values3">The third value array as a <see cref="Span{T}"/> of <typeparamref name="TValue3"/></param>
		/// <param name="values4">The fourth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue4"/></param>
		/// <param name="values5">The fifth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue5"/></param>
		/// <param name="values6">The sixth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue6"/></param>
		/// <param name="values7">The seventh value array as a <see cref="Span{T}"/> of <typeparamref name="TValue7"/></param>
		/// <param name="values8">The eighth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue8"/></param>
		/// <param name="values9">The ninth value array as a <see cref="Span{T}"/> of <typeparamref name="TValue9"/></param>
		/// <param name="comparer">The <see cref="Comparer{T}"/> of <typeparamref name="TKey"/> used to compare the elements in <paramref name="keys"/>. Default null means <see cref="Comparer{T}.Default"/>.</param>
		public static void Sort<TKey, TValue1, TValue2, TValue3, TValue4, TValue5, TValue6, TValue7, TValue8, TValue9>(this Span<TKey> keys, Span<TValue1> values1, Span<TValue2> values2, Span<TValue3> values3, Span<TValue4> values4, Span<TValue5> values5, Span<TValue6> values6, Span<TValue7> values7, Span<TValue8> values8, Span<TValue9> values9, Comparer<TKey>? comparer = null)
			where TValue1 : ISwapper<TValue1> where TValue2 : ISwapper<TValue2> where TValue3 : ISwapper<TValue3> where TValue4 : ISwapper<TValue4> where TValue5 : ISwapper<TValue5> where TValue6 : ISwapper<TValue6> where TValue7 : ISwapper<TValue7> where TValue8 : ISwapper<TValue8> where TValue9 : ISwapper<TValue9> 
		{
			SortHelper<TKey, TValue1, TValue2, TValue3, TValue4, TValue5, TValue6, TValue7, TValue8, TValue9>.Sort(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, comparer ?? Comparer<TKey>.Default);
		}

	}
	#endregion


	#region implementations
	internal static class SortHelper<TKey, TVal1>
		where TVal1 : ISwapper<TVal1> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, 0, i);
				MaximizeHeap(keys, values1, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	internal static class SortHelper<TKey, TVal1, TVal2>
		where TVal1 : ISwapper<TVal1> where TVal2 : ISwapper<TVal2> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, values2, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
					TVal2.Swap(ref values2[i], ref values2[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
			TVal2.Swap(ref values2[i], ref values2[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, values2, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, values2, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, values2, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, values2, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], values2[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], values2[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], values2[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], values2[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, values2, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, values2, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, values2, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, values2, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, values2, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, values2, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, values2, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, values2, 0, i);
				MaximizeHeap(keys, values1, values2, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, values2, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					TVal2.Swap(ref values2[j + 1], ref values2[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	internal static class SortHelper<TKey, TVal1, TVal2, TVal3>
		where TVal1 : ISwapper<TVal1> where TVal2 : ISwapper<TVal2> where TVal3 : ISwapper<TVal3> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, values2, values3, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
					TVal2.Swap(ref values2[i], ref values2[j]);
					TVal3.Swap(ref values3[i], ref values3[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
			TVal2.Swap(ref values2[i], ref values2[j]);
			TVal3.Swap(ref values3[i], ref values3[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, values2, values3, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, values2, values3, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, values2, values3, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, values2, values3, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], values2[..left], values3[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], values2[..left], values3[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], values2[..left], values3[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], values2[(partition + 1)..left], values3[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, values2, values3, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, values2, values3, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, values2, values3, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, values2, values3, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, values2, values3, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, values2, values3, 0, i);
				MaximizeHeap(keys, values1, values2, values3, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, values2, values3, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					TVal2.Swap(ref values2[j + 1], ref values2[j]);
					TVal3.Swap(ref values3[j + 1], ref values3[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	internal static class SortHelper<TKey, TVal1, TVal2, TVal3, TVal4>
		where TVal1 : ISwapper<TVal1> where TVal2 : ISwapper<TVal2> where TVal3 : ISwapper<TVal3> where TVal4 : ISwapper<TVal4> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, values2, values3, values4, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
					TVal2.Swap(ref values2[i], ref values2[j]);
					TVal3.Swap(ref values3[i], ref values3[j]);
					TVal4.Swap(ref values4[i], ref values4[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
			TVal2.Swap(ref values2[i], ref values2[j]);
			TVal3.Swap(ref values3[i], ref values3[j]);
			TVal4.Swap(ref values4[i], ref values4[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], values2[(partition + 1)..left], values3[(partition + 1)..left], values4[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, values2, values3, values4, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, values2, values3, values4, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, values2, values3, values4, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, values2, values3, values4, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, values2, values3, values4, 0, i);
				MaximizeHeap(keys, values1, values2, values3, values4, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, values2, values3, values4, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					TVal2.Swap(ref values2[j + 1], ref values2[j]);
					TVal3.Swap(ref values3[j + 1], ref values3[j]);
					TVal4.Swap(ref values4[j + 1], ref values4[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	internal static class SortHelper<TKey, TVal1, TVal2, TVal3, TVal4, TVal5>
		where TVal1 : ISwapper<TVal1> where TVal2 : ISwapper<TVal2> where TVal3 : ISwapper<TVal3> where TVal4 : ISwapper<TVal4> where TVal5 : ISwapper<TVal5> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, values2, values3, values4, values5, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
					TVal2.Swap(ref values2[i], ref values2[j]);
					TVal3.Swap(ref values3[i], ref values3[j]);
					TVal4.Swap(ref values4[i], ref values4[j]);
					TVal5.Swap(ref values5[i], ref values5[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
			TVal2.Swap(ref values2[i], ref values2[j]);
			TVal3.Swap(ref values3[i], ref values3[j]);
			TVal4.Swap(ref values4[i], ref values4[j]);
			TVal5.Swap(ref values5[i], ref values5[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], values2[(partition + 1)..left], values3[(partition + 1)..left], values4[(partition + 1)..left], values5[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, values2, values3, values4, values5, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, values2, values3, values4, values5, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, values2, values3, values4, values5, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, values2, values3, values4, values5, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, values2, values3, values4, values5, 0, i);
				MaximizeHeap(keys, values1, values2, values3, values4, values5, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, values2, values3, values4, values5, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					TVal2.Swap(ref values2[j + 1], ref values2[j]);
					TVal3.Swap(ref values3[j + 1], ref values3[j]);
					TVal4.Swap(ref values4[j + 1], ref values4[j]);
					TVal5.Swap(ref values5[j + 1], ref values5[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	internal static class SortHelper<TKey, TVal1, TVal2, TVal3, TVal4, TVal5, TVal6>
		where TVal1 : ISwapper<TVal1> where TVal2 : ISwapper<TVal2> where TVal3 : ISwapper<TVal3> where TVal4 : ISwapper<TVal4> where TVal5 : ISwapper<TVal5> where TVal6 : ISwapper<TVal6> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, values2, values3, values4, values5, values6, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
					TVal2.Swap(ref values2[i], ref values2[j]);
					TVal3.Swap(ref values3[i], ref values3[j]);
					TVal4.Swap(ref values4[i], ref values4[j]);
					TVal5.Swap(ref values5[i], ref values5[j]);
					TVal6.Swap(ref values6[i], ref values6[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
			TVal2.Swap(ref values2[i], ref values2[j]);
			TVal3.Swap(ref values3[i], ref values3[j]);
			TVal4.Swap(ref values4[i], ref values4[j]);
			TVal5.Swap(ref values5[i], ref values5[j]);
			TVal6.Swap(ref values6[i], ref values6[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], values2[(partition + 1)..left], values3[(partition + 1)..left], values4[(partition + 1)..left], values5[(partition + 1)..left], values6[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, values2, values3, values4, values5, values6, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, values2, values3, values4, values5, values6, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, values2, values3, values4, values5, values6, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, values2, values3, values4, values5, values6, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, values2, values3, values4, values5, values6, 0, i);
				MaximizeHeap(keys, values1, values2, values3, values4, values5, values6, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, values2, values3, values4, values5, values6, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					TVal2.Swap(ref values2[j + 1], ref values2[j]);
					TVal3.Swap(ref values3[j + 1], ref values3[j]);
					TVal4.Swap(ref values4[j + 1], ref values4[j]);
					TVal5.Swap(ref values5[j + 1], ref values5[j]);
					TVal6.Swap(ref values6[j + 1], ref values6[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	internal static class SortHelper<TKey, TVal1, TVal2, TVal3, TVal4, TVal5, TVal6, TVal7>
		where TVal1 : ISwapper<TVal1> where TVal2 : ISwapper<TVal2> where TVal3 : ISwapper<TVal3> where TVal4 : ISwapper<TVal4> where TVal5 : ISwapper<TVal5> where TVal6 : ISwapper<TVal6> where TVal7 : ISwapper<TVal7> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, values2, values3, values4, values5, values6, values7, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
					TVal2.Swap(ref values2[i], ref values2[j]);
					TVal3.Swap(ref values3[i], ref values3[j]);
					TVal4.Swap(ref values4[i], ref values4[j]);
					TVal5.Swap(ref values5[i], ref values5[j]);
					TVal6.Swap(ref values6[i], ref values6[j]);
					TVal7.Swap(ref values7[i], ref values7[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
			TVal2.Swap(ref values2[i], ref values2[j]);
			TVal3.Swap(ref values3[i], ref values3[j]);
			TVal4.Swap(ref values4[i], ref values4[j]);
			TVal5.Swap(ref values5[i], ref values5[j]);
			TVal6.Swap(ref values6[i], ref values6[j]);
			TVal7.Swap(ref values7[i], ref values7[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], values2[(partition + 1)..left], values3[(partition + 1)..left], values4[(partition + 1)..left], values5[(partition + 1)..left], values6[(partition + 1)..left], values7[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, values2, values3, values4, values5, values6, values7, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, values2, values3, values4, values5, values6, values7, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, 0, i);
				MaximizeHeap(keys, values1, values2, values3, values4, values5, values6, values7, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					TVal2.Swap(ref values2[j + 1], ref values2[j]);
					TVal3.Swap(ref values3[j + 1], ref values3[j]);
					TVal4.Swap(ref values4[j + 1], ref values4[j]);
					TVal5.Swap(ref values5[j + 1], ref values5[j]);
					TVal6.Swap(ref values6[j + 1], ref values6[j]);
					TVal7.Swap(ref values7[j + 1], ref values7[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	internal static class SortHelper<TKey, TVal1, TVal2, TVal3, TVal4, TVal5, TVal6, TVal7, TVal8>
		where TVal1 : ISwapper<TVal1> where TVal2 : ISwapper<TVal2> where TVal3 : ISwapper<TVal3> where TVal4 : ISwapper<TVal4> where TVal5 : ISwapper<TVal5> where TVal6 : ISwapper<TVal6> where TVal7 : ISwapper<TVal7> where TVal8 : ISwapper<TVal8> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, values2, values3, values4, values5, values6, values7, values8, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
					TVal2.Swap(ref values2[i], ref values2[j]);
					TVal3.Swap(ref values3[i], ref values3[j]);
					TVal4.Swap(ref values4[i], ref values4[j]);
					TVal5.Swap(ref values5[i], ref values5[j]);
					TVal6.Swap(ref values6[i], ref values6[j]);
					TVal7.Swap(ref values7[i], ref values7[j]);
					TVal8.Swap(ref values8[i], ref values8[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
			TVal2.Swap(ref values2[i], ref values2[j]);
			TVal3.Swap(ref values3[i], ref values3[j]);
			TVal4.Swap(ref values4[i], ref values4[j]);
			TVal5.Swap(ref values5[i], ref values5[j]);
			TVal6.Swap(ref values6[i], ref values6[j]);
			TVal7.Swap(ref values7[i], ref values7[j]);
			TVal8.Swap(ref values8[i], ref values8[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], values8[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], values8[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], values8[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], values2[(partition + 1)..left], values3[(partition + 1)..left], values4[(partition + 1)..left], values5[(partition + 1)..left], values6[(partition + 1)..left], values7[(partition + 1)..left], values8[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, values2, values3, values4, values5, values6, values7, values8, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, 0, i);
				MaximizeHeap(keys, values1, values2, values3, values4, values5, values6, values7, values8, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					TVal2.Swap(ref values2[j + 1], ref values2[j]);
					TVal3.Swap(ref values3[j + 1], ref values3[j]);
					TVal4.Swap(ref values4[j + 1], ref values4[j]);
					TVal5.Swap(ref values5[j + 1], ref values5[j]);
					TVal6.Swap(ref values6[j + 1], ref values6[j]);
					TVal7.Swap(ref values7[j + 1], ref values7[j]);
					TVal8.Swap(ref values8[j + 1], ref values8[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	internal static class SortHelper<TKey, TVal1, TVal2, TVal3, TVal4, TVal5, TVal6, TVal7, TVal8, TVal9>
		where TVal1 : ISwapper<TVal1> where TVal2 : ISwapper<TVal2> where TVal3 : ISwapper<TVal3> where TVal4 : ISwapper<TVal4> where TVal5 : ISwapper<TVal5> where TVal6 : ISwapper<TVal6> where TVal7 : ISwapper<TVal7> where TVal8 : ISwapper<TVal8> where TVal9 : ISwapper<TVal9> 
	{
		internal static void Sort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Span<TVal9> values9, Comparer<TKey> comparer)
		{
			if (keys.Length > 1)
			{
				IntroSort(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, depthLimit: 2 * (keys.Length.Log2() + 1), comparer);
			}
		}

		private static void SwapIfGreaterWithValues(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Span<TVal9> values9, Comparer<TKey> comparer, int i, int j)
		{
			if (comparer.Compare(keys[i], keys[j]) > 0)
			{
				TKey val = keys[i];
				keys[i] = keys[j];
				keys[j] = val;
					TVal1.Swap(ref values1[i], ref values1[j]);
					TVal2.Swap(ref values2[i], ref values2[j]);
					TVal3.Swap(ref values3[i], ref values3[j]);
					TVal4.Swap(ref values4[i], ref values4[j]);
					TVal5.Swap(ref values5[i], ref values5[j]);
					TVal6.Swap(ref values6[i], ref values6[j]);
					TVal7.Swap(ref values7[i], ref values7[j]);
					TVal8.Swap(ref values8[i], ref values8[j]);
					TVal9.Swap(ref values9[i], ref values9[j]);
			}
		}

		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void Swap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Span<TVal9> values9, int i, int j)
		{
			TKey val = keys[i];
			keys[i] = keys[j];
			keys[j] = val;
			TVal1.Swap(ref values1[i], ref values1[j]);
			TVal2.Swap(ref values2[i], ref values2[j]);
			TVal3.Swap(ref values3[i], ref values3[j]);
			TVal4.Swap(ref values4[i], ref values4[j]);
			TVal5.Swap(ref values5[i], ref values5[j]);
			TVal6.Swap(ref values6[i], ref values6[j]);
			TVal7.Swap(ref values7[i], ref values7[j]);
			TVal8.Swap(ref values8[i], ref values8[j]);
			TVal9.Swap(ref values9[i], ref values9[j]);
		}

		private static void IntroSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Span<TVal9> values9, int depthLimit, Comparer<TKey> comparer)
		{
			int left = keys.Length;
			while (left > 1)
			{
				if (left <= 16)
				{
					switch (left)
					{
						case 2:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, comparer, 0, 1);
							break;
						case 3:
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, comparer, 0, 1);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, comparer, 0, 2);
							SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, comparer, 1, 2);
							break;
						default:
							InsertionSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], values8[..left], values9[..left], comparer);
							break;
					}
					break;
				}
				if (depthLimit == 0)
				{
					HeapSort(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], values8[..left], values9[..left], comparer);
					break;
				}
				depthLimit--;
				int partition = PickPivotAndPartition(keys[..left], values1[..left], values2[..left], values3[..left], values4[..left], values5[..left], values6[..left], values7[..left], values8[..left], values9[..left], comparer);
				IntroSort(keys[(partition + 1)..left], values1[(partition + 1)..left], values2[(partition + 1)..left], values3[(partition + 1)..left], values4[(partition + 1)..left], values5[(partition + 1)..left], values6[(partition + 1)..left], values7[(partition + 1)..left], values8[(partition + 1)..left], values9[(partition + 1)..left], depthLimit, comparer);
				left = partition;
			}
		}

		private static int PickPivotAndPartition(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Span<TVal9> values9, Comparer<TKey> comparer)
		{
			int maxN = keys.Length - 1;
			int halfN = maxN >> 1;
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, comparer, 0, halfN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, comparer, 0, maxN);
			SwapIfGreaterWithValues(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, comparer, halfN, maxN);
			TKey val = keys[halfN];
			Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, halfN, maxN - 1);
			int count = 0;
			int left = maxN - 1;
			while (count < left)
			{
				while (comparer.Compare(keys[++count], val) < 0)
				{ }
				while (comparer.Compare(val, keys[--left]) < 0)
				{ }
				if (count >= left)
				{
					break;
				}
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, count, left);
			}
			if (count != maxN - 1)
			{
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, count, maxN - 1);
			}
			return count;
		}

		private static void HeapSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Span<TVal9> values9, Comparer<TKey> comparer)
		{
			int length = keys.Length;
			for (int i = length / 2 - 1; i >= 0; i--)
			{
				MaximizeHeap(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, i, length, comparer);
			}
			for (int i = length - 1; i > 0; i--)
			{
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, 0, i);
				MaximizeHeap(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, 0, i, comparer);
			}
		}

		private static void MaximizeHeap(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Span<TVal9> values9, int start, int end, Comparer<TKey> comparer)
		{
			int parent = start, child = parent * 2 + 1;
			while (child < end)
			{
				if (child + 1 < end && comparer.Compare(keys[child], keys[child + 1]) < 0)
					child++;
				if (comparer.Compare(keys[parent], keys[child]) > 0)
					return;
				Swap(keys, values1, values2, values3, values4, values5, values6, values7, values8, values9, parent, child);
				parent = child;
				child = parent * 2 + 1;
			}
		}

		private static void InsertionSort(Span<TKey> keys, Span<TVal1> values1, Span<TVal2> values2, Span<TVal3> values3, Span<TVal4> values4, Span<TVal5> values5, Span<TVal6> values6, Span<TVal7> values7, Span<TVal8> values8, Span<TVal9> values9, Comparer<TKey> comparer)
		{
			for (int i = 1; i < keys.Length - 1; i++)
			{
				TKey key0 = keys[i + 1];
				int j = i - 1;
				while (j >= 0 && comparer.Compare(key0, keys[j]) < 0)
				{
					keys[j + 1] = keys[j];
					TVal1.Swap(ref values1[j + 1], ref values1[j]);
					TVal2.Swap(ref values2[j + 1], ref values2[j]);
					TVal3.Swap(ref values3[j + 1], ref values3[j]);
					TVal4.Swap(ref values4[j + 1], ref values4[j]);
					TVal5.Swap(ref values5[j + 1], ref values5[j]);
					TVal6.Swap(ref values6[j + 1], ref values6[j]);
					TVal7.Swap(ref values7[j + 1], ref values7[j]);
					TVal8.Swap(ref values8[j + 1], ref values8[j]);
					TVal9.Swap(ref values9[j + 1], ref values9[j]);
					j--;
				}
				keys[j + 1] = key0;
			}
		}
	}
	#endregion
}
