// NOTICE:
// This file is generated by corresponding ".tt" file template, do NOT modify this file.

using System.Linq.Expressions;

using Althea.SourceGenerator;
using Althea.Storage;

namespace Althea.LinearAlgebra.Dense
{
	/// <summary>
	/// The abstract interface for dense linear algebra extend BLAS API routines which involves runtime parsing <see cref="Expression"/>s.
	/// </summary>
	/// <remarks>Since <see cref="Expression"/> is a class (therefore introduces GC) and must be parsed before calculation, it is not recommended to use this API for non-critical situations.</remarks>
	[AbstractRuntimeApi]
	public interface IExpressionExtendBlasAbstractApi : IAbstractRuntimeApi<IExpressionExtendBlasAbstractApi>
	{
		#region vector operations
		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="output"/>[i] = <paramref name="op"/>(<paramref name="input"/>[i])</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T}"/> to apply to each elements of <paramref name="input"/></param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		
		/// <param name="output">The output vector to store the result of <paramref name="op"/></param>
		/// <param name="strideOut">The stride of output vector</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T>> op, TS1 input, long strideIn, TS2 output, long strideOut) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, perform inclusive partial aggregate (scan) <paramref name="op"/> with parameters as the elements in <paramref name="input"/> and returns as the result to be written in <paramref name="output"/>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T}"/> to apply to each elements of <paramref name="input"/> and <paramref name="output"/></param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		/// <param name="output">The output vector to store the result of <paramref name="op"/></param>
		/// <param name="strideOut">The stride of output vector</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsScan<T, TS1, TS2>(Expression<Func<T, T, T>> op, TS1 input, long strideIn, TS2 output, long strideOut) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute reduction: <c>result = <paramref name="op"/>(<paramref name="input"/>[i], result)</c> for all <c>i</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TOut">The output data type</typeparam>
		/// <typeparam name="TS">The actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, TOut, TOut}"/> to apply to each elements of <paramref name="input"/> and partial result</param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		/// <param name="result">Output the reduction result of <paramref name="input"/> under <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsReduce<T, TOut, TS>(Expression<Func<T, TOut, TOut>> op, TS input, long strideIn, out TOut result) where T : unmanaged, IBaseNumber<T> where TS : class, IStorage<T, TS>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="output"/>[i] = <paramref name="op"/>(<paramref name="input"/>[i], <paramref name="scalar"/>)</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T}"/> to apply to each elements of <paramref name="input"/> and <paramref name="scalar"/></param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		/// <param name="scalar">The scalar input to apply <paramref name="op"/></param>
		/// <param name="output">The output vector to store the result of <paramref name="op"/></param>
		/// <param name="strideOut">The stride of output vector</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, T>> op, TS1 input, long strideIn, T scalar, TS2 output, long strideOut) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="output"/>[i] = <paramref name="op"/>(<paramref name="input"/>[i], <paramref name="scalars"/>)</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, T}"/> to apply to each elements of <paramref name="input"/> and <paramref name="scalars"/></param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		/// <param name="scalars">The scalar inputs to apply <paramref name="op"/></param>
		/// <param name="output">The output vector to store the result of <paramref name="op"/></param>
		/// <param name="strideOut">The stride of output vector</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, T, T>> op, TS1 input, long strideIn, ReadOnlySpan<T> scalars, TS2 output, long strideOut) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="outputs"/>[i] = <paramref name="op"/>(<paramref name="input"/>[i])</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, TOutputs}"/> to apply to each elements of <paramref name="input"/></param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		
		/// <param name="outputs">The output vectors and strides to store the results of <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, (T Out1, T Out2)>> op, TS1 input, long strideIn, ReadOnlySpan<(TS2 Vector, long Stride)> outputs) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, perform inclusive partial aggregate (scan) <paramref name="op"/> with parameters as the elements in <paramref name="input"/> and returns as the result to be written in <paramref name="outputs"/>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, TOutputs}"/> to apply to each elements of <paramref name="input"/> and <paramref name="outputs"/></param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		/// <param name="outputs">The output vectors and strides to store the results of <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsScan<T, TS1, TS2>(Expression<Func<T, T, T, (T Out1, T Out2)>> op, TS1 input, long strideIn, ReadOnlySpan<(TS2 Vector, long Stride)> outputs) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="outputs"/>[i] = <paramref name="op"/>(<paramref name="input"/>[i], <paramref name="scalar"/>)</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, TOutputs}"/> to apply to each elements of <paramref name="input"/> and <paramref name="scalar"/></param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		/// <param name="scalar">The scalar input to apply <paramref name="op"/></param>
		/// <param name="outputs">The output vectors and strides to store the results of <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, (T Out1, T Out2)>> op, TS1 input, long strideIn, T scalar, ReadOnlySpan<(TS2 Vector, long Stride)> outputs) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="outputs"/>[i] = <paramref name="op"/>(<paramref name="input"/>[i], <paramref name="scalars"/>)</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, TOutputs}"/> to apply to each elements of <paramref name="input"/> and <paramref name="scalars"/></param>
		/// <param name="input">The input vector to apply <paramref name="op"/></param>
		/// <param name="strideIn">The stride of input vector</param>
		/// <param name="scalars">The scalar inputs to apply <paramref name="op"/></param>
		/// <param name="outputs">The output vectors and strides to store the results of <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, T, (T Out1, T Out2)>> op, TS1 input, long strideIn, ReadOnlySpan<T> scalars, ReadOnlySpan<(TS2 Vector, long Stride)> outputs) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="output"/>[i] = <paramref name="op"/>(<paramref name="inputs"/>[i])</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T}"/> to apply to each elements of <paramref name="inputs"/></param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		
		/// <param name="output">The output vector to store the result of <paramref name="op"/></param>
		/// <param name="strideOut">The stride of output vector</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, T>> op, ReadOnlySpan<(TS1 Vector, long Stride)> inputs, TS2 output, long strideOut) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, perform inclusive partial aggregate (scan) <paramref name="op"/> with parameters as the elements in <paramref name="inputs"/> and returns as the result to be written in <paramref name="output"/>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, T}"/> to apply to each elements of <paramref name="inputs"/> and <paramref name="output"/></param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		/// <param name="output">The output vector to store the result of <paramref name="op"/></param>
		/// <param name="strideOut">The stride of output vector</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsScan<T, TS1, TS2>(Expression<Func<T, T, T, T>> op, ReadOnlySpan<(TS1 Vector, long Stride)> inputs, TS2 output, long strideOut) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute reduction: <c>result = <paramref name="op"/>(<paramref name="inputs"/>[i], result)</c> for all <c>i</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TOut">The output data type</typeparam>
		/// <typeparam name="TS">The actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, TOut, TOut}"/> to apply to each elements of <paramref name="inputs"/> and partial result</param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		/// <param name="result">Output the reduction result of <paramref name="inputs"/> under <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsReduce<T, TOut, TS>(Expression<Func<T, T, TOut, TOut>> op, ReadOnlySpan<(TS Vector, long Stride)> inputs, out TOut result) where T : unmanaged, IBaseNumber<T> where TS : class, IStorage<T, TS>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="output"/>[i] = <paramref name="op"/>(<paramref name="inputs"/>[i], <paramref name="scalar"/>)</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, T}"/> to apply to each elements of <paramref name="inputs"/> and <paramref name="scalar"/></param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		/// <param name="scalar">The scalar input to apply <paramref name="op"/></param>
		/// <param name="output">The output vector to store the result of <paramref name="op"/></param>
		/// <param name="strideOut">The stride of output vector</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, T, T>> op, ReadOnlySpan<(TS1 Vector, long Stride)> inputs, T scalar, TS2 output, long strideOut) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="output"/>[i] = <paramref name="op"/>(<paramref name="inputs"/>[i], <paramref name="scalars"/>)</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, T, T}"/> to apply to each elements of <paramref name="inputs"/> and <paramref name="scalars"/></param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		/// <param name="scalars">The scalar inputs to apply <paramref name="op"/></param>
		/// <param name="output">The output vector to store the result of <paramref name="op"/></param>
		/// <param name="strideOut">The stride of output vector</param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, T, T, T>> op, ReadOnlySpan<(TS1 Vector, long Stride)> inputs, ReadOnlySpan<T> scalars, TS2 output, long strideOut) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="outputs"/>[i] = <paramref name="op"/>(<paramref name="inputs"/>[i])</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, TOutputs}"/> to apply to each elements of <paramref name="inputs"/></param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		
		/// <param name="outputs">The output vectors and strides to store the results of <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, (T Out1, T Out2)>> op, ReadOnlySpan<(TS1 Vector, long Stride)> inputs, ReadOnlySpan<(TS2 Vector, long Stride)> outputs) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, perform inclusive partial aggregate (scan) <paramref name="op"/> with parameters as the elements in <paramref name="inputs"/> and returns as the result to be written in <paramref name="outputs"/>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, T, TOutputs}"/> to apply to each elements of <paramref name="inputs"/> and <paramref name="outputs"/></param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		/// <param name="outputs">The output vectors and strides to store the results of <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsScan<T, TS1, TS2>(Expression<Func<T, T, T, T, (T Out1, T Out2)>> op, ReadOnlySpan<(TS1 Vector, long Stride)> inputs, ReadOnlySpan<(TS2 Vector, long Stride)> outputs) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="outputs"/>[i] = <paramref name="op"/>(<paramref name="inputs"/>[i], <paramref name="scalar"/>)</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, TOutputs}"/> to apply to each elements of <paramref name="inputs"/> and <paramref name="scalar"/></param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		/// <param name="scalar">The scalar input to apply <paramref name="op"/></param>
		/// <param name="outputs">The output vectors and strides to store the results of <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, T, (T Out1, T Out2)>> op, ReadOnlySpan<(TS1 Vector, long Stride)> inputs, T scalar, ReadOnlySpan<(TS2 Vector, long Stride)> outputs) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		/// <summary>
		/// When implemented by a derived class, compute point-wise update: <c><paramref name="outputs"/>[i] = <paramref name="op"/>(<paramref name="inputs"/>[i], <paramref name="scalars"/>)</c>.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number struct as the data type</typeparam>
		/// <typeparam name="TS1">The input actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TS2">The output actual storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="op">The <see cref="Expression{TDelegate}"/> of <see cref="Func{T, T, T, T, TOutputs}"/> to apply to each elements of <paramref name="inputs"/> and <paramref name="scalars"/></param>
		/// <param name="inputs">The input vectors and strides to apply <paramref name="op"/></param>
		/// <param name="scalars">The scalar inputs to apply <paramref name="op"/></param>
		/// <param name="outputs">The output vectors and strides to store the results of <paramref name="op"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the vectors is invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool GeneralVectorsPointwise<T, TS1, TS2>(Expression<Func<T, T, T, T, (T Out1, T Out2)>> op, ReadOnlySpan<(TS1 Vector, long Stride)> inputs, ReadOnlySpan<T> scalars, ReadOnlySpan<(TS2 Vector, long Stride)> outputs) where T : unmanaged, IBaseNumber<T> where TS1 : class, IStorage<T, TS1> where TS2 : class, IStorage<T, TS2>;

		#endregion
	}
}