using System;
using System.Runtime.InteropServices;


namespace Althea.Rng.Cuda
{
	/// <summary>
	/// CUDA random number generator API
	/// </summary>
	public static class NativeMethods
	{
		/// <summary>
		/// The CUDA Rand library name
		/// </summary>
		public const string CURAND_API_DLL_NAME = @"curand";

		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandCreateGenerator(ref IntPtr generator, GeneratorType rng_type);

		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandDestroyGenerator(IntPtr generator);

		/// <summary>
		/// Set the seed value of the pseudo-random number generator. All values of seed are valid.  Different seeds will produce different sequences. Different seeds will often not be statistically correlated with each other, but some pairs of seed values may generate sequences which are statistically correlated.
		/// </summary>
		/// <returns>Status</returns>
		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandSetPseudoRandomGeneratorSeed(IntPtr generator, long seed);

		/// <summary>
		/// Set the absolute offset of the pseudo or quasi-random number generator.
		/// <br/>
		/// All values of offset are valid.  The offset position is absolute, not relative to the current position in the sequence.
		/// </summary>
		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandSetGeneratorOffset(IntPtr generator, long offset);

		/// <summary>
		/// Set the ordering of results of the pseudo or quasi-random number generator.
		/// </summary>
		/// <param name="generator">Legal values of order for pseudo-random generators are:<br/>
		/// <list type="bullet">
		/// <item>
		/// <description><see cref="Ordering.PseudoDefault"/></description>
		/// </item>
		/// <item>
		/// <description><see cref="Ordering.PseudoBest"/></description>
		/// </item>
		/// <item>
		/// <description><see cref="Ordering.Pseudoeseded"/></description>
		/// </item>
		/// </list>
		/// </param>
		/// <param name="order">Legal values of order for quasi-random generator is <see cref="Ordering.QuasiDefault"/></param>
		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandSetGeneratorOrdering(IntPtr generator, Ordering order);

		/// <summary>
		/// Set the number of dimensions to be generated by the quasi-random number generator.
		/// <para/>
		/// Legal values for <paramref name="num_dimensions"/> are 1 to 20000.
		/// </summary>
		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandSetQuasiRandomGeneratorDimensions(IntPtr generator, int num_dimensions);

		/// <summary>
		/// Use generator to generate <paramref name="num"/> 32-bit results into the device memory at <paramref name="outputPtr"/>. The device memory must have been previously allocated and be large enough to hold all the results. <br/>
		/// Launches are done with the stream or the null stream if no stream has been set.<para/>
		/// Results are 32-bit <see cref="int"/> with every bit random.
		/// </summary>
		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandGenerate(IntPtr generator, IntPtr outputPtr, long num);

		/// <summary>
		/// Use generator to generate <paramref name="num"/> 64-bit results into the device memory at <paramref name="outputPtr"/>. The device memory must have been previously allocated and be large enough to hold all the results. <br/>
		/// Launches are done with the stream or the null stream if no stream has been set.<para/>
		/// Results are 64-bit <see cref="long"/> with every bit random.
		/// </summary>
		/// <returns>Status</returns>
		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandGenerateLongLong(IntPtr generator, IntPtr outputPtr, long num);

		/// <summary>
		/// Use generator to generate <paramref name="num"/> 32-bit results into the device memory at <paramref name="outputPtr"/>. The device memory must have been previously allocated and be large enough to hold all the results. <br/>
		/// Launches are done with the stream or the null stream if no stream has been set.<para/>
		/// Results are 32-bit <see cref="float"/> between 0.0f and 1.0f, (0.0f, 1.0f] for specify.
		/// </summary>
		/// <returns>Status</returns>
		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandGenerateUniform(IntPtr generator, IntPtr outputPtr, long num);

		/// <summary>
		/// Use generator to generate <paramref name="num"/> 64-bit results into the device memory at <paramref name="outputPtr"/>. The device memory must have been previously allocated and be large enough to hold all the results. <br/>
		/// Launches are done with the stream or the null stream if no stream has been set.<para/>
		/// Results are 64-bit <see cref="double"/> between 0.0d and 1.0d, (0.0d, 1.0d] for specify.
		/// </summary>
		/// <returns>Status</returns>
		[DllImport(CURAND_API_DLL_NAME)]
		//[NativeMethodBoundary]
		internal static extern Status curandGenerateUniformDouble(IntPtr generator, IntPtr outputPtr, long num);
	}
}
