// NOTICE:
// This file is generated by corresponding ".tt" file template, do NOT modify this file.

using System.Runtime.CompilerServices;


namespace Althea.Numerics;


public readonly partial struct Double
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(Double value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(Double value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out Double result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (double)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (double)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (double)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (double)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (double)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (double)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (double)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (double)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (double)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (double)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (double)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (double)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (double)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out Double result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((double)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((double)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((double)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((double)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((double)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((double)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((double)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((double)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((double)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((double)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((double)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((double)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((double)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct Single
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(Single value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(Single value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out Single result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (float)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (float)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (float)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (float)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (float)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (float)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (float)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (float)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (float)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (float)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (float)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (float)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (float)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out Single result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((float)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((float)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((float)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((float)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((float)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((float)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((float)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((float)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((float)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((float)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((float)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((float)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((float)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct Half
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(Half value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(Half value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out Half result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (System.Half)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (System.Half)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (System.Half)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (System.Half)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (System.Half)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (System.Half)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (System.Half)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (System.Half)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (System.Half)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (System.Half)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (System.Half)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (System.Half)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (System.Half)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out Half result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((System.Half)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((System.Half)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((System.Half)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((System.Half)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((System.Half)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((System.Half)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((System.Half)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((System.Half)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((System.Half)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((System.Half)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((System.Half)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((System.Half)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((System.Half)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct Int8
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(Int8 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(Int8 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out Int8 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (sbyte)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (sbyte)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (sbyte)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (sbyte)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (sbyte)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (sbyte)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (sbyte)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (sbyte)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (sbyte)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (sbyte)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (sbyte)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (sbyte)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (sbyte)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out Int8 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((sbyte)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((sbyte)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((sbyte)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((sbyte)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((sbyte)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((sbyte)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((sbyte)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((sbyte)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((sbyte)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((sbyte)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((sbyte)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((sbyte)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((sbyte)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct Int16
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(Int16 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(Int16 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out Int16 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (short)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (short)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (short)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (short)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (short)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (short)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (short)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (short)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (short)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (short)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (short)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (short)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (short)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out Int16 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((short)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((short)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((short)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((short)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((short)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((short)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((short)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((short)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((short)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((short)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((short)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((short)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((short)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct Int32
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(Int32 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(Int32 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out Int32 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (int)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (int)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (int)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (int)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (int)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (int)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (int)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (int)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (int)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (int)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (int)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (int)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (int)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out Int32 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((int)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((int)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((int)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((int)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((int)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((int)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((int)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((int)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((int)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((int)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((int)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((int)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((int)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct Int64
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(Int64 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(Int64 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out Int64 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (long)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (long)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (long)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (long)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (long)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (long)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (long)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (long)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (long)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (long)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (long)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (long)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (long)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out Int64 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((long)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((long)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((long)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((long)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((long)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((long)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((long)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((long)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((long)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((long)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((long)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((long)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((long)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct Int128
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(Int128 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(Int128 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out Int128 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (System.Int128)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (System.Int128)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (System.Int128)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (System.Int128)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (System.Int128)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (System.Int128)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (System.Int128)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (System.Int128)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (System.Int128)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (System.Int128)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (System.Int128)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (System.Int128)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (System.Int128)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out Int128 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((System.Int128)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((System.Int128)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((System.Int128)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((System.Int128)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((System.Int128)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((System.Int128)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((System.Int128)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((System.Int128)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((System.Int128)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((System.Int128)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((System.Int128)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((System.Int128)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((System.Int128)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct UInt8
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(UInt8 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(UInt8 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out UInt8 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (byte)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (byte)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (byte)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (byte)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (byte)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (byte)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (byte)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (byte)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (byte)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (byte)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (byte)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (byte)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (byte)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out UInt8 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((byte)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((byte)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((byte)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((byte)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((byte)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((byte)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((byte)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((byte)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((byte)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((byte)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((byte)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((byte)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((byte)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct UInt16
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(UInt16 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(UInt16 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out UInt16 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (ushort)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (ushort)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (ushort)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (ushort)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (ushort)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (ushort)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (ushort)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (ushort)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (ushort)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (ushort)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (ushort)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (ushort)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (ushort)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out UInt16 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((ushort)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((ushort)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((ushort)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((ushort)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((ushort)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((ushort)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((ushort)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((ushort)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((ushort)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((ushort)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((ushort)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((ushort)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((ushort)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct UInt32
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(UInt32 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(UInt32 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out UInt32 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (uint)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (uint)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (uint)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (uint)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (uint)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (uint)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (uint)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (uint)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (uint)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (uint)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (uint)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (uint)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (uint)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out UInt32 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((uint)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((uint)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((uint)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((uint)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((uint)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((uint)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((uint)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((uint)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((uint)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((uint)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((uint)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((uint)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((uint)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct UInt64
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(UInt64 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(UInt64 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out UInt64 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (ulong)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (ulong)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (ulong)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (ulong)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (ulong)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (ulong)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (ulong)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (ulong)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (ulong)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (ulong)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (ulong)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (ulong)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (ulong)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out UInt64 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((ulong)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((ulong)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((ulong)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((ulong)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((ulong)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((ulong)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((ulong)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((ulong)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((ulong)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((ulong)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((ulong)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((ulong)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((ulong)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}


public readonly partial struct UInt128
{
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertTo<TOther>(UInt128 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = (double)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = (float)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = (System.Half)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = (sbyte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = (short)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = (int)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = (long)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = (System.Int128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = (byte)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = (ushort)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = (uint)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = (ulong)value._value;
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = (System.UInt128)value._value;
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertToChecked<TOther>(UInt128 value, out TOther result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			var v = checked((double)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			var v = checked((float)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			var v = checked((System.Half)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			var v = checked((sbyte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			var v = checked((short)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			var v = checked((int)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			var v = checked((long)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			var v = checked((System.Int128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			var v = checked((byte)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			var v = checked((ushort)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			var v = checked((uint)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			var v = checked((ulong)value._value);
			result = *(TOther*)&v;
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			var v = checked((System.UInt128)value._value);
			result = *(TOther*)&v;
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFrom<TOther>(TOther value, out UInt128 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = (System.UInt128)(*(double*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = (System.UInt128)(*(float*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = (System.UInt128)(*(System.Half*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = (System.UInt128)(*(sbyte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = (System.UInt128)(*(short*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = (System.UInt128)(*(int*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = (System.UInt128)(*(long*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = (System.UInt128)(*(System.Int128*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = (System.UInt128)(*(byte*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = (System.UInt128)(*(ushort*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = (System.UInt128)(*(uint*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = (System.UInt128)(*(ulong*)&value);
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = (System.UInt128)(*(System.UInt128*)&value);
			return true;
		}
		result = default;
		return false;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static unsafe bool TryConvertFromChecked<TOther>(TOther value, out UInt128 result) where TOther : unmanaged, INumber<TOther>
	{
		if (typeof(TOther) == typeof(Double))
		{
			result = checked((System.UInt128)(*(double*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Single))
		{
			result = checked((System.UInt128)(*(float*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Half))
		{
			result = checked((System.UInt128)(*(System.Half*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int8))
		{
			result = checked((System.UInt128)(*(sbyte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int16))
		{
			result = checked((System.UInt128)(*(short*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int32))
		{
			result = checked((System.UInt128)(*(int*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int64))
		{
			result = checked((System.UInt128)(*(long*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(Int128))
		{
			result = checked((System.UInt128)(*(System.Int128*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt8))
		{
			result = checked((System.UInt128)(*(byte*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt16))
		{
			result = checked((System.UInt128)(*(ushort*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt32))
		{
			result = checked((System.UInt128)(*(uint*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt64))
		{
			result = checked((System.UInt128)(*(ulong*)&value));
			return true;
		}
		if (typeof(TOther) == typeof(UInt128))
		{
			result = checked((System.UInt128)(*(System.UInt128*)&value));
			return true;
		}
		result = default;
		return false;
	}
}
