// NOTICE:
// This file is generated by corresponding ".tt" file template, do NOT modify this file.

using System.Globalization;
using System.Runtime.CompilerServices;
using System.Numerics;


namespace Althea.Numerics;


/// <summary>
/// The custom replacement of <see cref="double"/> that implements <see cref="IBinaryFloat{TSelf}"/>.
/// </summary>
public readonly partial struct Float64 : IBinaryFloat<Float64>
{
	private readonly double _value;

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	private Float64(double v) => this._value = v;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator Float64(double v) => new(v);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator double(Float64 v) => v._value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool Equals(Float64 other) => this == other;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override bool Equals(object? obj) => this._value.Equals(obj);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override int GetHashCode() => this._value.GetHashCode();

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public int CompareTo(object? obj) => this._value.CompareTo(obj);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public int CompareTo(Float64 other) => this._value.CompareTo(other);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider) => this._value.TryFormat(destination, out charsWritten, format, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override string ToString() => this._value.ToString();

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string ToString(string? format, IFormatProvider? formatProvider) => this._value.ToString(format, formatProvider);

	/// <inheritdoc/>
	public static DataType Type => DataType.RealFloat64;

	/// <inheritdoc/>
	public static Float64 MachinePrecision => 2.220446049250313E-16;

	/// <inheritdoc/>
	public static unsafe int Size => sizeof(double);

	/// <inheritdoc/>
	public static bool IsComplexType => false;

	/// <inheritdoc/>
	public static Float64 One => 1.0;

	/// <inheritdoc/>
	public static Float64 Zero => 0.0;
	
	/// <inheritdoc/>
	public static Float64 NegativeOne => -1.0;

	/// <inheritdoc/>
	public static Float64 NegativeZero => -0.0;

	/// <inheritdoc/>
	public static Float64 AdditiveIdentity => 0.0;

	/// <inheritdoc/>
	public static Float64 MultiplicativeIdentity => 1.0;

	/// <inheritdoc/>
	public static Float64 NaN => double.NaN;
	/// <inheritdoc/>
	public static Float64 NegativeInfinity => double.NegativeInfinity;
	/// <inheritdoc/>
	public static Float64 PositiveInfinity => double.PositiveInfinity;
	/// <inheritdoc/>
	public static Float64 E => double.E;
	/// <inheritdoc/>
	public static Float64 Epsilon => double.Epsilon;
	/// <inheritdoc/>
	public static Float64 Pi => double.Pi;
	/// <inheritdoc/>
	public static Float64 Tau => double.Tau;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsReal(Float64 value) => true;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsComplex(Float64 value) => false;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsImaginaryNumber(Float64 value) => false;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsZero(Float64 value) => value._value == 0.0;
	
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Sign(Float64 value) => (double)double.Sign(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Conjugate(Float64 value) => value;

	/// <inheritdoc/>
	public static bool TryParse(string? s, IFormatProvider? provider, out Float64 result)
	{
		bool success = double.TryParse(s, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out Float64 result)
	{
		bool success = double.TryParse(s, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(string? s, NumberStyles style, IFormatProvider? provider, out Float64 result)
	{
		bool success = double.TryParse(s, style, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out Float64 result)
	{
		bool success = double.TryParse(s, style, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Ceiling(Float64 x) => double.Ceiling(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Floor(Float64 x) => double.Floor(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Round(Float64 x) => double.Round(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Round(Float64 x, int digits) => double.Round(x, digits);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Round(Float64 x, MidpointRounding mode) => double.Round(x, mode);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Round(Float64 x, int digits, MidpointRounding mode) => double.Round(x, digits, mode);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Truncate(Float64 x) => double.Truncate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 FusedMultiplyAdd(Float64 left, Float64 right, Float64 addend) => double.FusedMultiplyAdd(left, right, addend);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 ReciprocalEstimate(Float64 x) => double.ReciprocalEstimate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 ReciprocalSqrtEstimate(Float64 x) => double.ReciprocalSqrtEstimate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsFinite(Float64 value) => double.IsFinite(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsNaN(Float64 value) => double.IsNaN(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsNegative(Float64 value) => double.IsNegative(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsPositive(Float64 value) => double.IsPositive(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsInteger(Float64 value) => double.IsInteger(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsOddInteger(Float64 value) => double.IsOddInteger(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Abs(Float64 value) => double.Abs(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 MaxMagnitude(Float64 x, Float64 y) => double.MaxMagnitude(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 MaxMagnitudeNumber(Float64 x, Float64 y) => double.MaxMagnitudeNumber(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 MinMagnitude(Float64 x, Float64 y) => double.MinMagnitude(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 MinMagnitudeNumber(Float64 x, Float64 y) => double.MinMagnitudeNumber(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 CopySign(Float64 value, Float64 sign) => double.CopySign(value, sign);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Max(Float64 x, Float64 y) => double.Max(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Min(Float64 x, Float64 y) => double.Min(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Parse(string s, IFormatProvider? provider) => double.Parse(s, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Parse(string s, NumberStyles style, IFormatProvider? provider) => double.Parse(s, style, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => double.Parse(s, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) => double.Parse(s, style, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Acosh(Float64 x) => double.Acosh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Asinh(Float64 x) => double.Asinh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Atanh(Float64 x) => double.Atanh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Cosh(Float64 x) => double.Cosh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Sinh(Float64 x) => double.Sinh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Tanh(Float64 x) => double.Tanh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Log(Float64 x) => double.Log(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Log(Float64 x, Float64 newBase) => double.Log(x, newBase);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 LogP1(Float64 x) => double.LogP1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Log2(Float64 x) => double.Log2(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Log2P1(Float64 x) => double.Log2P1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Log10(Float64 x) => double.Log10(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Log10P1(Float64 x) => double.Log10P1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Pow(Float64 x, Float64 y) => double.Pow(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Cbrt(Float64 x) => double.Cbrt(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Sqrt(Float64 x) => double.Sqrt(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Acos(Float64 x) => double.Acos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Asin(Float64 x) => double.Asin(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Atan(Float64 x) => double.Atan(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Atan2(Float64 y, Float64 x) => double.Atan2(y, x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Cos(Float64 x) => double.Cos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Sin(Float64 x) => double.Sin(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static (Float64 Sin, Float64 Cos) SinCos(Float64 x) => double.SinCos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Tan(Float64 x) => double.Tan(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Exp(Float64 x) => double.Exp(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 ExpM1(Float64 x) => double.ExpM1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Exp2(Float64 x) => double.Exp2(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Exp2M1(Float64 x) => double.Exp2M1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Exp10(Float64 x) => double.Exp10(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 Exp10M1(Float64 x) => double.Exp10M1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator <(Float64 left, Float64 right) => left._value < right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator <=(Float64 left, Float64 right) => left._value <= right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator >(Float64 left, Float64 right) => left._value > right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator >=(Float64 left, Float64 right) => left._value >= right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator ==(Float64 left, Float64 right) => left._value == right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator !=(Float64 left, Float64 right) => left._value != right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 operator +(Float64 left, Float64 right) => left._value + right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 operator -(Float64 left, Float64 right) => left._value - right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 operator *(Float64 left, Float64 right) => left._value * right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 operator /(Float64 left, Float64 right) => left._value / right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 operator -(Float64 value) => -value._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 operator +(Float64 value) => +value._value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 operator ++(Float64 value)
	{
		var v = value._value;
		++v;
		return v;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float64 operator --(Float64 value)
	{
		var v = value._value;
		--v;
		return v;
	}
	
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float64 IIncrementOperators<Float64>.op_CheckedIncrement(Float64 value) => ++value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float64 IDecrementOperators<Float64>.op_CheckedDecrement(Float64 value) => --value;

		/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float64 IAdditionOperators<Float64, Float64, Float64>.op_CheckedAddition(Float64 left, Float64 right) => checked(left._value + right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float64 ISubtractionOperators<Float64, Float64, Float64>.op_CheckedSubtraction(Float64 left, Float64 right) => checked(left._value - right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float64 IMultiplyOperators<Float64, Float64, Float64>.op_CheckedMultiply(Float64 left, Float64 right) => checked(left._value * right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float64 IDivisionOperators<Float64, Float64, Float64>.op_CheckedDivision(Float64 left, Float64 right) => checked(left._value / right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float64 IUnaryNegationOperators<Float64, Float64>.op_CheckedUnaryNegation(Float64 value) => checked(-value._value);
}


/// <summary>
/// The custom replacement of <see cref="float"/> that implements <see cref="IBinaryFloat{TSelf}"/>.
/// </summary>
public readonly partial struct Float32 : IBinaryFloat<Float32>
{
	private readonly float _value;

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	private Float32(float v) => this._value = v;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator Float32(float v) => new(v);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator float(Float32 v) => v._value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool Equals(Float32 other) => this == other;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override bool Equals(object? obj) => this._value.Equals(obj);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override int GetHashCode() => this._value.GetHashCode();

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public int CompareTo(object? obj) => this._value.CompareTo(obj);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public int CompareTo(Float32 other) => this._value.CompareTo(other);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider) => this._value.TryFormat(destination, out charsWritten, format, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override string ToString() => this._value.ToString();

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string ToString(string? format, IFormatProvider? formatProvider) => this._value.ToString(format, formatProvider);

	/// <inheritdoc/>
	public static DataType Type => DataType.RealFloat32;

	/// <inheritdoc/>
	public static Float32 MachinePrecision => 1.1920928955078125E-07F;

	/// <inheritdoc/>
	public static unsafe int Size => sizeof(float);

	/// <inheritdoc/>
	public static bool IsComplexType => false;

	/// <inheritdoc/>
	public static Float32 One => 1.0F;

	/// <inheritdoc/>
	public static Float32 Zero => 0.0F;
	
	/// <inheritdoc/>
	public static Float32 NegativeOne => -1.0F;

	/// <inheritdoc/>
	public static Float32 NegativeZero => -0.0F;

	/// <inheritdoc/>
	public static Float32 AdditiveIdentity => 0.0F;

	/// <inheritdoc/>
	public static Float32 MultiplicativeIdentity => 1.0F;

	/// <inheritdoc/>
	public static Float32 NaN => float.NaN;
	/// <inheritdoc/>
	public static Float32 NegativeInfinity => float.NegativeInfinity;
	/// <inheritdoc/>
	public static Float32 PositiveInfinity => float.PositiveInfinity;
	/// <inheritdoc/>
	public static Float32 E => float.E;
	/// <inheritdoc/>
	public static Float32 Epsilon => float.Epsilon;
	/// <inheritdoc/>
	public static Float32 Pi => float.Pi;
	/// <inheritdoc/>
	public static Float32 Tau => float.Tau;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsReal(Float32 value) => true;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsComplex(Float32 value) => false;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsImaginaryNumber(Float32 value) => false;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsZero(Float32 value) => value._value == 0.0F;
	
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Sign(Float32 value) => (float)float.Sign(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Conjugate(Float32 value) => value;

	/// <inheritdoc/>
	public static bool TryParse(string? s, IFormatProvider? provider, out Float32 result)
	{
		bool success = float.TryParse(s, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out Float32 result)
	{
		bool success = float.TryParse(s, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(string? s, NumberStyles style, IFormatProvider? provider, out Float32 result)
	{
		bool success = float.TryParse(s, style, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out Float32 result)
	{
		bool success = float.TryParse(s, style, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Ceiling(Float32 x) => float.Ceiling(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Floor(Float32 x) => float.Floor(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Round(Float32 x) => float.Round(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Round(Float32 x, int digits) => float.Round(x, digits);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Round(Float32 x, MidpointRounding mode) => float.Round(x, mode);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Round(Float32 x, int digits, MidpointRounding mode) => float.Round(x, digits, mode);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Truncate(Float32 x) => float.Truncate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 FusedMultiplyAdd(Float32 left, Float32 right, Float32 addend) => float.FusedMultiplyAdd(left, right, addend);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 ReciprocalEstimate(Float32 x) => float.ReciprocalEstimate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 ReciprocalSqrtEstimate(Float32 x) => float.ReciprocalSqrtEstimate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsFinite(Float32 value) => float.IsFinite(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsNaN(Float32 value) => float.IsNaN(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsNegative(Float32 value) => float.IsNegative(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsPositive(Float32 value) => float.IsPositive(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsInteger(Float32 value) => float.IsInteger(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsOddInteger(Float32 value) => float.IsOddInteger(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Abs(Float32 value) => float.Abs(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 MaxMagnitude(Float32 x, Float32 y) => float.MaxMagnitude(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 MaxMagnitudeNumber(Float32 x, Float32 y) => float.MaxMagnitudeNumber(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 MinMagnitude(Float32 x, Float32 y) => float.MinMagnitude(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 MinMagnitudeNumber(Float32 x, Float32 y) => float.MinMagnitudeNumber(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 CopySign(Float32 value, Float32 sign) => float.CopySign(value, sign);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Max(Float32 x, Float32 y) => float.Max(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Min(Float32 x, Float32 y) => float.Min(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Parse(string s, IFormatProvider? provider) => float.Parse(s, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Parse(string s, NumberStyles style, IFormatProvider? provider) => float.Parse(s, style, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => float.Parse(s, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) => float.Parse(s, style, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Acosh(Float32 x) => float.Acosh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Asinh(Float32 x) => float.Asinh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Atanh(Float32 x) => float.Atanh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Cosh(Float32 x) => float.Cosh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Sinh(Float32 x) => float.Sinh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Tanh(Float32 x) => float.Tanh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Log(Float32 x) => float.Log(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Log(Float32 x, Float32 newBase) => float.Log(x, newBase);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 LogP1(Float32 x) => float.LogP1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Log2(Float32 x) => float.Log2(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Log2P1(Float32 x) => float.Log2P1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Log10(Float32 x) => float.Log10(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Log10P1(Float32 x) => float.Log10P1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Pow(Float32 x, Float32 y) => float.Pow(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Cbrt(Float32 x) => float.Cbrt(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Sqrt(Float32 x) => float.Sqrt(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Acos(Float32 x) => float.Acos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Asin(Float32 x) => float.Asin(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Atan(Float32 x) => float.Atan(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Atan2(Float32 y, Float32 x) => float.Atan2(y, x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Cos(Float32 x) => float.Cos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Sin(Float32 x) => float.Sin(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static (Float32 Sin, Float32 Cos) SinCos(Float32 x) => float.SinCos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Tan(Float32 x) => float.Tan(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Exp(Float32 x) => float.Exp(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 ExpM1(Float32 x) => float.ExpM1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Exp2(Float32 x) => float.Exp2(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Exp2M1(Float32 x) => float.Exp2M1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Exp10(Float32 x) => float.Exp10(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 Exp10M1(Float32 x) => float.Exp10M1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator <(Float32 left, Float32 right) => left._value < right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator <=(Float32 left, Float32 right) => left._value <= right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator >(Float32 left, Float32 right) => left._value > right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator >=(Float32 left, Float32 right) => left._value >= right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator ==(Float32 left, Float32 right) => left._value == right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator !=(Float32 left, Float32 right) => left._value != right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 operator +(Float32 left, Float32 right) => left._value + right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 operator -(Float32 left, Float32 right) => left._value - right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 operator *(Float32 left, Float32 right) => left._value * right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 operator /(Float32 left, Float32 right) => left._value / right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 operator -(Float32 value) => -value._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 operator +(Float32 value) => +value._value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 operator ++(Float32 value)
	{
		var v = value._value;
		++v;
		return v;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float32 operator --(Float32 value)
	{
		var v = value._value;
		--v;
		return v;
	}
	
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float32 IIncrementOperators<Float32>.op_CheckedIncrement(Float32 value) => ++value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float32 IDecrementOperators<Float32>.op_CheckedDecrement(Float32 value) => --value;

		/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float32 IAdditionOperators<Float32, Float32, Float32>.op_CheckedAddition(Float32 left, Float32 right) => checked(left._value + right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float32 ISubtractionOperators<Float32, Float32, Float32>.op_CheckedSubtraction(Float32 left, Float32 right) => checked(left._value - right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float32 IMultiplyOperators<Float32, Float32, Float32>.op_CheckedMultiply(Float32 left, Float32 right) => checked(left._value * right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float32 IDivisionOperators<Float32, Float32, Float32>.op_CheckedDivision(Float32 left, Float32 right) => checked(left._value / right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float32 IUnaryNegationOperators<Float32, Float32>.op_CheckedUnaryNegation(Float32 value) => checked(-value._value);
}


/// <summary>
/// The custom replacement of <see cref="Half"/> that implements <see cref="IBinaryFloat{TSelf}"/>.
/// </summary>
public readonly partial struct Float16 : IBinaryFloat<Float16>
{
	private readonly Half _value;

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	private Float16(Half v) => this._value = v;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator Float16(Half v) => new(v);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static implicit operator Half(Float16 v) => v._value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool Equals(Float16 other) => this == other;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override bool Equals(object? obj) => this._value.Equals(obj);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override int GetHashCode() => this._value.GetHashCode();

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public int CompareTo(object? obj) => this._value.CompareTo(obj);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public int CompareTo(Float16 other) => this._value.CompareTo(other);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider) => this._value.TryFormat(destination, out charsWritten, format, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public override string ToString() => this._value.ToString();

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string ToString(string? format, IFormatProvider? formatProvider) => this._value.ToString(format, formatProvider);

	/// <inheritdoc/>
	public static DataType Type => DataType.RealFloat16;

	/// <inheritdoc/>
	public static Float16 MachinePrecision => (Half)0.0009765625F;

	/// <inheritdoc/>
	public static unsafe int Size => sizeof(Half);

	/// <inheritdoc/>
	public static bool IsComplexType => false;

	/// <inheritdoc/>
	public static Float16 One => Half.One;

	/// <inheritdoc/>
	public static Float16 Zero => Half.Zero;
	
	/// <inheritdoc/>
	public static Float16 NegativeOne => Half.NegativeOne;

	/// <inheritdoc/>
	public static Float16 NegativeZero => Half.NegativeZero;

	/// <inheritdoc/>
	public static Float16 AdditiveIdentity => Half.Zero;

	/// <inheritdoc/>
	public static Float16 MultiplicativeIdentity => Half.One;

	/// <inheritdoc/>
	public static Float16 NaN => Half.NaN;
	/// <inheritdoc/>
	public static Float16 NegativeInfinity => Half.NegativeInfinity;
	/// <inheritdoc/>
	public static Float16 PositiveInfinity => Half.PositiveInfinity;
	/// <inheritdoc/>
	public static Float16 E => Half.E;
	/// <inheritdoc/>
	public static Float16 Epsilon => Half.Epsilon;
	/// <inheritdoc/>
	public static Float16 Pi => Half.Pi;
	/// <inheritdoc/>
	public static Float16 Tau => Half.Tau;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsReal(Float16 value) => true;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsComplex(Float16 value) => false;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsImaginaryNumber(Float16 value) => false;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsZero(Float16 value) => value._value == Half.Zero;
	
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Sign(Float16 value) => (Half)Half.Sign(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Conjugate(Float16 value) => value;

	/// <inheritdoc/>
	public static bool TryParse(string? s, IFormatProvider? provider, out Float16 result)
	{
		bool success = Half.TryParse(s, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out Float16 result)
	{
		bool success = Half.TryParse(s, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(string? s, NumberStyles style, IFormatProvider? provider, out Float16 result)
	{
		bool success = Half.TryParse(s, style, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out Float16 result)
	{
		bool success = Half.TryParse(s, style, provider, out var res);
		result = res;
		return success;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Ceiling(Float16 x) => Half.Ceiling(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Floor(Float16 x) => Half.Floor(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Round(Float16 x) => Half.Round(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Round(Float16 x, int digits) => Half.Round(x, digits);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Round(Float16 x, MidpointRounding mode) => Half.Round(x, mode);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Round(Float16 x, int digits, MidpointRounding mode) => Half.Round(x, digits, mode);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Truncate(Float16 x) => Half.Truncate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 FusedMultiplyAdd(Float16 left, Float16 right, Float16 addend) => Half.FusedMultiplyAdd(left, right, addend);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 ReciprocalEstimate(Float16 x) => Half.ReciprocalEstimate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 ReciprocalSqrtEstimate(Float16 x) => Half.ReciprocalSqrtEstimate(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsFinite(Float16 value) => Half.IsFinite(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsNaN(Float16 value) => Half.IsNaN(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsNegative(Float16 value) => Half.IsNegative(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsPositive(Float16 value) => Half.IsPositive(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsInteger(Float16 value) => Half.IsInteger(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool IsOddInteger(Float16 value) => Half.IsOddInteger(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Abs(Float16 value) => Half.Abs(value);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 MaxMagnitude(Float16 x, Float16 y) => Half.MaxMagnitude(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 MaxMagnitudeNumber(Float16 x, Float16 y) => Half.MaxMagnitudeNumber(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 MinMagnitude(Float16 x, Float16 y) => Half.MinMagnitude(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 MinMagnitudeNumber(Float16 x, Float16 y) => Half.MinMagnitudeNumber(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 CopySign(Float16 value, Float16 sign) => Half.CopySign(value, sign);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Max(Float16 x, Float16 y) => Half.Max(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Min(Float16 x, Float16 y) => Half.Min(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Parse(string s, IFormatProvider? provider) => Half.Parse(s, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Parse(string s, NumberStyles style, IFormatProvider? provider) => Half.Parse(s, style, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => Half.Parse(s, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) => Half.Parse(s, style, provider);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Acosh(Float16 x) => Half.Acosh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Asinh(Float16 x) => Half.Asinh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Atanh(Float16 x) => Half.Atanh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Cosh(Float16 x) => Half.Cosh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Sinh(Float16 x) => Half.Sinh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Tanh(Float16 x) => Half.Tanh(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Log(Float16 x) => Half.Log(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Log(Float16 x, Float16 newBase) => Half.Log(x, newBase);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 LogP1(Float16 x) => Half.LogP1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Log2(Float16 x) => Half.Log2(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Log2P1(Float16 x) => Half.Log2P1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Log10(Float16 x) => Half.Log10(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Log10P1(Float16 x) => Half.Log10P1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Pow(Float16 x, Float16 y) => Half.Pow(x, y);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Cbrt(Float16 x) => Half.Cbrt(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Sqrt(Float16 x) => Half.Sqrt(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Acos(Float16 x) => Half.Acos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Asin(Float16 x) => Half.Asin(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Atan(Float16 x) => Half.Atan(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Atan2(Float16 y, Float16 x) => Half.Atan2(y, x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Cos(Float16 x) => Half.Cos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Sin(Float16 x) => Half.Sin(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static (Float16 Sin, Float16 Cos) SinCos(Float16 x) => Half.SinCos(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Tan(Float16 x) => Half.Tan(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Exp(Float16 x) => Half.Exp(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 ExpM1(Float16 x) => Half.ExpM1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Exp2(Float16 x) => Half.Exp2(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Exp2M1(Float16 x) => Half.Exp2M1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Exp10(Float16 x) => Half.Exp10(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 Exp10M1(Float16 x) => Half.Exp10M1(x);

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator <(Float16 left, Float16 right) => left._value < right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator <=(Float16 left, Float16 right) => left._value <= right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator >(Float16 left, Float16 right) => left._value > right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator >=(Float16 left, Float16 right) => left._value >= right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator ==(Float16 left, Float16 right) => left._value == right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static bool operator !=(Float16 left, Float16 right) => left._value != right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 operator +(Float16 left, Float16 right) => left._value + right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 operator -(Float16 left, Float16 right) => left._value - right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 operator *(Float16 left, Float16 right) => left._value * right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 operator /(Float16 left, Float16 right) => left._value / right._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 operator -(Float16 value) => -value._value;
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 operator +(Float16 value) => +value._value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 operator ++(Float16 value)
	{
		var v = value._value;
		++v;
		return v;
	}

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static Float16 operator --(Float16 value)
	{
		var v = value._value;
		--v;
		return v;
	}
	
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float16 IIncrementOperators<Float16>.op_CheckedIncrement(Float16 value) => ++value;

	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float16 IDecrementOperators<Float16>.op_CheckedDecrement(Float16 value) => --value;

		/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float16 IAdditionOperators<Float16, Float16, Float16>.op_CheckedAddition(Float16 left, Float16 right) => checked(left._value + right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float16 ISubtractionOperators<Float16, Float16, Float16>.op_CheckedSubtraction(Float16 left, Float16 right) => checked(left._value - right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float16 IMultiplyOperators<Float16, Float16, Float16>.op_CheckedMultiply(Float16 left, Float16 right) => checked(left._value * right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float16 IDivisionOperators<Float16, Float16, Float16>.op_CheckedDivision(Float16 left, Float16 right) => checked(left._value / right._value);
	/// <inheritdoc/>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	static Float16 IUnaryNegationOperators<Float16, Float16>.op_CheckedUnaryNegation(Float16 value) => checked(-value._value);
}
