// NOTICE:
// This file is generated by corresponding ".tt" file template, do NOT modify this file.

using Althea.SourceGenerator;
using Althea.Storage;


namespace Althea.LinearAlgebra.Sparse
{
	/// <summary>
	/// The abstract interface for runtime extended index related operation API routines 
	/// </summary>
	[AbstractRuntimeApi]
	public interface IExtendIndexOperationAbstractApi : IAbstractRuntimeApi<IExtendIndexOperationAbstractApi>
	{
		/// <summary>
		/// When implemented by a derived class, sort the elements of the given integer-typed <paramref name="keys"/> with all given values.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number as the key type</typeparam>
		/// <typeparam name="TS">The concrete storage type for keys that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T1">Any unmanaged number as the first value type</typeparam>
		/// <typeparam name="TS1">The concrete storage type for first values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second value type</typeparam>
		/// <typeparam name="TS2">The concrete storage type for second values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="keys">The storage of the key array to be sorted</param>
		/// <param name="strideKeys">The stride between consecutive elements in <paramref name="keys"/></param>
		/// <param name="values1">The storage of the first value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues1">The stride between consecutive elements in <paramref name="values1"/></param>
		/// <param name="values2">The storage of the second value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues2">The stride between consecutive elements in <paramref name="values2"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool Sort<T, TS, T1, TS1, T2, TS2>(TS keys, long strideKeys, TS1 values1, long strideValues1, TS2 values2, long strideValues2) where T : unmanaged, IBaseNumber<T> where TS : class, IStorage<T, TS> where T1 : unmanaged, IBaseNumber<T1> where TS1 : class, IStorage<T1, TS1> where T2 : unmanaged, IBaseNumber<T2> where TS2 : class, IStorage<T2, TS2>;

		/// <summary>
		/// When implemented by a derived class, sort the elements of the given integer-typed <paramref name="keys"/> with all given values.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number as the key type</typeparam>
		/// <typeparam name="TS">The concrete storage type for keys that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T1">Any unmanaged number as the first value type</typeparam>
		/// <typeparam name="TS1">The concrete storage type for first values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second value type</typeparam>
		/// <typeparam name="TS2">The concrete storage type for second values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third value type</typeparam>
		/// <typeparam name="TS3">The concrete storage type for third values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="keys">The storage of the key array to be sorted</param>
		/// <param name="strideKeys">The stride between consecutive elements in <paramref name="keys"/></param>
		/// <param name="values1">The storage of the first value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues1">The stride between consecutive elements in <paramref name="values1"/></param>
		/// <param name="values2">The storage of the second value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues2">The stride between consecutive elements in <paramref name="values2"/></param>
		/// <param name="values3">The storage of the third value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues3">The stride between consecutive elements in <paramref name="values3"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool Sort<T, TS, T1, TS1, T2, TS2, T3, TS3>(TS keys, long strideKeys, TS1 values1, long strideValues1, TS2 values2, long strideValues2, TS3 values3, long strideValues3) where T : unmanaged, IBaseNumber<T> where TS : class, IStorage<T, TS> where T1 : unmanaged, IBaseNumber<T1> where TS1 : class, IStorage<T1, TS1> where T2 : unmanaged, IBaseNumber<T2> where TS2 : class, IStorage<T2, TS2> where T3 : unmanaged, IBaseNumber<T3> where TS3 : class, IStorage<T3, TS3>;

		/// <summary>
		/// When implemented by a derived class, sort the elements of the given integer-typed <paramref name="keys"/> with all given values.
		/// </summary>
		/// <typeparam name="T">Any unmanaged number as the key type</typeparam>
		/// <typeparam name="TS">The concrete storage type for keys that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T1">Any unmanaged number as the first value type</typeparam>
		/// <typeparam name="TS1">The concrete storage type for first values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T2">Any unmanaged number as the second value type</typeparam>
		/// <typeparam name="TS2">The concrete storage type for second values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T3">Any unmanaged number as the third value type</typeparam>
		/// <typeparam name="TS3">The concrete storage type for third values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="T4">Any unmanaged number as the fourth value type</typeparam>
		/// <typeparam name="TS4">The concrete storage type for fourth values that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="keys">The storage of the key array to be sorted</param>
		/// <param name="strideKeys">The stride between consecutive elements in <paramref name="keys"/></param>
		/// <param name="values1">The storage of the first value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues1">The stride between consecutive elements in <paramref name="values1"/></param>
		/// <param name="values2">The storage of the second value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues2">The stride between consecutive elements in <paramref name="values2"/></param>
		/// <param name="values3">The storage of the third value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues3">The stride between consecutive elements in <paramref name="values3"/></param>
		/// <param name="values4">The storage of the fourth value array to be sorted with <paramref name="keys"/></param>
		/// <param name="strideValues4">The stride between consecutive elements in <paramref name="values4"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If any of the storages is null or invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If any of the strides ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool Sort<T, TS, T1, TS1, T2, TS2, T3, TS3, T4, TS4>(TS keys, long strideKeys, TS1 values1, long strideValues1, TS2 values2, long strideValues2, TS3 values3, long strideValues3, TS4 values4, long strideValues4) where T : unmanaged, IBaseNumber<T> where TS : class, IStorage<T, TS> where T1 : unmanaged, IBaseNumber<T1> where TS1 : class, IStorage<T1, TS1> where T2 : unmanaged, IBaseNumber<T2> where TS2 : class, IStorage<T2, TS2> where T3 : unmanaged, IBaseNumber<T3> where TS3 : class, IStorage<T3, TS3> where T4 : unmanaged, IBaseNumber<T4> where TS4 : class, IStorage<T4, TS4>;

		/// <summary>
		/// When implemented by a derived class, sort the elements of the given integer-typed <paramref name="key"/> with <paramref name="values"/>.
		/// </summary>
		/// <typeparam name="TKey">Any unmanaged number as the key type</typeparam>
		/// <typeparam name="TSKey">The concrete storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <typeparam name="TVal">Any unmanaged number as the value type</typeparam>
		/// <typeparam name="TSVal">The concrete storage type that implements <see cref="IStorage{T, TSelf}"/></typeparam>
		/// <param name="key">The storage of the key array to be sorted</param>
		/// <param name="values">The storages of the value arrays to be sorted</param>
		/// <param name="strideKey">The stride between consecutive elements in <paramref name="key"/></param>
		/// <param name="strideValues">The strides between consecutive elements of each <paramref name="values"/></param>
		/// <returns>Whether this implementation supports the given parameters or not. If false, further internal operation is not allowed.</returns>
		/// <exception cref="ArgumentNullException">If <paramref name="key"/> or any of <paramref name="values"/> is null or invalid</exception>
		/// <exception cref="ArgumentOutOfRangeException">If <paramref name="strideKey"/> or  any of <paramref name="strideValues"/> ≤ 0</exception>
		[AbstractApiMethod]
		public abstract bool Sort<TKey, TVal, TSKey, TSVal>(TSKey key, long strideKey, ReadOnlySpan<TSVal> values, ReadOnlySpan<long> strideValues) where TKey : unmanaged, IBaseNumber<TKey> where TSKey : class, IStorage<TKey, TSKey> where TVal : unmanaged, IBaseNumber<TVal> where TSVal : class, IStorage<TVal, TSVal>;
	}
}