//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Althea.Backend {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Althea.Backend.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create the delegate of {0}. 的本地化字符串。
        /// </summary>
        internal static string CannotCreateDelegate {
            get {
                return ResourceManager.GetString("CannotCreateDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Krylov subspace algorithm: now at iteration {0}, {1} passed since last output. 的本地化字符串。
        /// </summary>
        internal static string IterationAndTimeInfo {
            get {
                return ResourceManager.GetString("IterationAndTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restarting Lanczos algorithm found that the {0} eigen-pair converges. 的本地化字符串。
        /// </summary>
        internal static string LanczosConvergeOnePair {
            get {
                return ResourceManager.GetString("LanczosConvergeOnePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Naïve Lanczos algorithm main calculation finishes, α = {0}, β = {0}. 的本地化字符串。
        /// </summary>
        internal static string NaiveLanczosFinish {
            get {
                return ResourceManager.GetString("NaiveLanczosFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Naïve Lanczos algorithm without restarting statrs with matrix size = {0} and maximum number of iteration = {1}. 的本地化字符串。
        /// </summary>
        internal static string NaiveLanczosStart {
            get {
                return ResourceManager.GetString("NaiveLanczosStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restarting Lanczos algorithm converged after {0} restarts. 的本地化字符串。
        /// </summary>
        internal static string RestartLanczosConverge {
            get {
                return ResourceManager.GetString("RestartLanczosConverge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restarting Lanczos algorithm failed to converged after {0} restarts, still {1} eigen-pairs left. 的本地化字符串。
        /// </summary>
        internal static string RestartLanczosFail {
            get {
                return ResourceManager.GetString("RestartLanczosFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restarting Lanczos algorithm statrs with matrix size = {0} and maximum number of restarts = {1}. 的本地化字符串。
        /// </summary>
        internal static string RestartLanczosStart {
            get {
                return ResourceManager.GetString("RestartLanczosStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of smallest eigenvalues required ({0}) is larger than the desired value, maybe the native eigen solver is a better option. 的本地化字符串。
        /// </summary>
        internal static string TooMuchEigenvaluesRequired {
            get {
                return ResourceManager.GetString("TooMuchEigenvaluesRequired", resourceCulture);
            }
        }
    }
}
